### ISSUE TITLE
Handle multiple TLS versions out of the box

### ISSUE THREAD

**Issue by sigmavirus24** [kennethreitz/requests#1570]
There are occasional cases where we could tell a server that we also support a lesser version of TLS when connecting to them and negotiate to a lower version if necessary.

This might reduce the noise we get on the issue tracker about making requests that result in SSLErrors. A great deal of the discussion around this has already taken place over on https://github.com/kennethreitz/requests/issues/1567

I'm still trying to discern how much work would be necessary to support this but I can not image it being too much.

**Comment by Lukasa** [comment]
My understanding is that this is not how TLS works. From [Technet](http://technet.microsoft.com/en-us/library/cc785811.aspx):

> **Client Hello**. The client initiates a session by sending a Client Hello message to the server. The Client Hello message contains:
> 
> > **Version Number**. The client sends the version number corresponding to the highest version it supports. Version 2 is used for SSL 2.0, version 3 for SSL 3.0, and version 3.1 for TLS. Although the IETF RFC for TLS is TLS version 1.0, the protocol uses 3.1 in the version field to indicate that it is a higher level (newer and with more functionality) than SSL 3.0.

So we can't do this as part of a handshake. Instead, we'd have to make the initial request, fail (in some nonspecific way) and then reattempt the handshake using a lower version. That seems like a slightly crazy thing to do, especially as the number one reason for failing a handshake has got to be attempting a TLS connection to a server that doesn't support it at all.

Unless I'm wrong about any of that, I'm -1 on this. =)

**Comment by sigmavirus24** [comment]
This is totally unrelated, but we also need a label that says "Needs Minion Input"

**Comment by t-8ch** [comment]
@sigmavirus24 That was not a `SSLError` but a `socket.error` which doesn't really indicate a SSL problem.

**Comment by sigmavirus24** [comment]
@t-8ch maybe I wasn't clear but I never said that issue was caused by this, just that discussion about negotiating a different version could be found there. =)

**Comment by karanlyons** [comment]
Low hanging fruit, but could we just add a "Maybe this server needs a lesser version of TLS? {link_to_docs}" when an HTTPS connection is reset by peer? It doesn't solve the actual problem, but at least points the dev in potentially the right direction.

(FWIW, I just happened to figure out what was going on after a bunch of debugging because I searched the issues for "connection reset by peer". Not _before_ I had opened a new issue, though.)

**Comment by Lukasa** [comment]
I wonder if this should be fixed in urllib3, and then caught and rethrown in Requests. My specific concern is that urllib3 has been wrapping these in `urllib3.exceptions.MaxRetriesError`s, which makes finding the original exception just that bit more of a pain. Presumably the `urllib3.VerifiedHTTPSConnection` object can catch this failure though.

That seems like the way to go to me.

**Comment by Lukasa** [comment]
In fact, I think that's the _right_ thing to do. I don't think we should renegotiate TLS for people without telling them: that feels like a step too far. Better to raise a `requests.SSLHandshakeError` and let the user handle this themselves.

**Comment by sigmavirus24** [comment]
@karanlyons could you submit a PR for that documentation? You have greater context on the issue than I do.
