### ISSUE TITLE
API for reporting failing URLs

### ISSUE THREAD

**Issue by kennethreitz** [kennethreitz/requests#1848]

**Comment by sigmavirus24** [comment]
Hm?

**Comment by kennethreitz** [comment]
Like a place to POST to http://report.python-requests.org/ when you have a URL that doesn't behave properly.

**Comment by sigmavirus24** [comment]
Ah okay

**Comment by kevinburke** [comment]
Failing in what sense? Non-conformant, serving 500's...

**Comment by sigmavirus24** [comment]
On Fri, Jan 10, 2014 at 04:48:02PM -0800, Kevin Burke wrote:

> Failing in what sense? Non-conformant, serving 500's...

We're not looking for twilio's list of horrible servers and websites that 
cause y'all headaches :P

I think this issue was motivated by the fact that we have been getting a lot 
of bug reports which focus more around one specific URL misbehaving and ends 
with us debugging the service for the user.

**Comment by grampajoe** [comment]
How would this be implemented? Is it for Requests developers, users, or someone else?

**Comment by shshank** [comment]
How about adding a report functionality, where you specify the reporting, which defaults to report.python-requests.org ? I would like to implement this, once we have a clear idea on exactly what we want to report.

**Comment by shshank** [comment]
I mean where we specify the reporting URL.

**Comment by Lukasa** [comment]
The primary use-case here is to avoid Kenneth getting spammed with bug reports in his inbox that basically go: "This website doesn't work for me in Requests". I'm open to this being a more general service like @shshank suggested, but right now our interest is in getting that crud off Kenneth's plate and onto mine and @sigmavirus24's. =)
