### ISSUE TITLE
Allow a 'verbose' flag for raise_for_status()

### ISSUE THREAD

**Issue by mrname** [kennethreitz/requests#2402]
raise_for_status() is super awesome, but a lot of the time, the error code and message is not informative enough to assist with debgugging when an exception is raised. It would be nice to have a verbose flag for raise_for_status that would also print the response body, where more details are often included. I would be happy to work on this, but wanted to make sure it is not already in the works.

**Comment by sigmavirus24** [comment]
If you do:

``` py
import requests

r = requests.get(url)

try:
    r.raise_for_status()
except requests.exceptions.HTTPError as error:
    print(error)
    print(error.response.text)
```

We don't print the body (and likely won't add it, even as a flag) for several reasons:
- It may not exist (and therefore wouldn't be helpful)
- It could be plain binary data which will certainly not help anyone
- It could have characters that cannot be printed (and will cause even more problems)

You can certainly do this yourself and based on some searches on StackOverflow and our issues, it doesn't seem like anyone has had the need for this before.

I'm -0.5 if only because `verbose` would obviously default to `False`.

**Comment by mrname** [comment]
Thanks for the quick response @sigmavirus24. That makes a lot of sense. I was thinking that a verbose flag would avoid the need for the try/except structure, but it is simple enough to a make a little helper function that processes the request and does that. Thanks again! Please go ahead and close this out.

**Comment by revmischa** [comment]
Verbose flag would be very nice
