### ISSUE TITLE
Cookie header isn't passed when redirected

### ISSUE THREAD

**Issue by Fizzadar** [kennethreitz/requests#2416]
The `Cookie` header isn't sent to redirected URL's like other headers is:

```
# Requests version = 2.5.1

ipdb> response.request.headers
{'CustomHeader': 'this_still_works!'}
ipdb> response.history[0].request.headers
{'CustomHeader': 'this_still_works!', 'Cookie': 'token=top_secret_token; email="dev@dev.com";'}
```

**Comment by sigmavirus24** [comment]
There isn't enough information to even begin to debug this. You're clearly being redirected.
- Are you being redirected to new domain (or sub-domain)? (e.g., from `example.com` to `sub.example.com` or `example.org`)
- Are you being redirected from `http://` to `https://`?
- Where does the cookie come from?
  - Do you specify it yourself?
  - Is it in a cookie-jar to start with?
  - Are you using a session that collected the cookie for you?

These are just starting questions. I guarantee I'll have more once you answer them.

**Comment by Fizzadar** [comment]
Apologies @sigmavirus24, definitely short on info:
- Redirect is append-slash like (`dev.local/api/test` -> `dev.local/api/test/`)
- Both served over HTTP
- Cookie is set in the headers dict passed to `requests.get`, no jar/session

Let me know if you need anything else.

**Comment by sigmavirus24** [comment]
So we [rebuild](https://github.com/kennethreitz/requests/blob/d2d576b6b1101e2871c82f63adf2c2b534c2dabc/requests/sessions.py#L168..L176) the `Cookie` header on a redirect as a matter of not exposing the cookie to people who shouldn't see it. Without a cookiejar to rebuild _from_ we won't persist the header through the redirect. We already [sanitize authorization](https://github.com/kennethreitz/requests/blob/d2d576b6b1101e2871c82f63adf2c2b534c2dabc/requests/sessions.py#L215) on redirect to different hosts, so we _could_ do the same here.

I want @Lukasa's thoughts on this though before I continue with work for this.

I, for one, think Cookie headers are in the same class as Content-Length and Host headers. They can be set by users but they really _shouldn't_ be set by users because it can do bad things if not handled with care.

**Comment by Lukasa** [comment]
Agreed, cookies set in the headers have an unclear scope, so we assume their scope is extremely tight. I think that's a good behaviour.

**Comment by Fizzadar** [comment]
I agree, it's too much like "cookie injection" to send cookies as custom headers through redirects :)
