### ISSUE TITLE
Ampersand (&) added for no reason?

### ISSUE THREAD

**Issue by GAZ082** [kennethreitz/requests#2463]
Hi guys, could you confirm if this is a bug or works as intended?

```python

import requests
import json

url = "http://server:8080/jsonrpc?request=";
headers = {'content-type': 'application/json'};
payload = {blah};

r = requests.get(url, params=json.dumps(payload), headers=headers);

print(r.url);

```

It outputs the encoded string BUT for no reason adds an ampersand as below:

http://server:8080/jsonrpc?request=**&**{blah}

This provokes parse errors when querying XBMC/KODI server.

Thanks!

**Comment by Lukasa** [comment]
It is indeed working as intended.

The problem is this: we have no real way of knowing what you mean when you provide part of the query string as part of the URL and part in the 'params' section. You're doing something particularly unexpected by passing parameters as a string rather than a mapping (though I suspect that's for the sake of this limited example and not your actual code).

The position is generally that if you want us to build your query string you should let us build the whole thing, or at least build whole name-value pairs. Don't ask us to build a part of a name-value pair, because it's really hard to see when that's intended behaviour.

I don't really consider this a bug, more a sharp edge in the API.

**Comment by GAZ082** [comment]
Mmmm. So basically, i messed it up when put **?request=**

**Comment by sigmavirus24** [comment]
@GAZ082 the following should work:

``` py
import requests
import json

url = "http://server:8080/jsonrpc";
headers = {'content-type': 'application/json'};
payload = {'foo': 'bar'}
params = {'request': json.dumps(payload)}

r = requests.get(url, params=params, headers=headers)

print(r.url)
```

In the future though, questions like this will be answered quickly on [StackOverflow](https://stackoverflow.com/questions/tagged/python-requests)

**Comment by GAZ082** [comment]
Thank you sigma.
