### ISSUE TITLE
RuntimeWarning when using eventlet for patching requests

### ISSUE THREAD

**Issue by imazor** [kennethreitz/requests#2469]
Hi,
I am getting the following warning while using requests with eventlet:
/usr/local/lib/python2.7/site-packages/requests/utils.py:74: RuntimeWarning: Parent module 'requests' not found while handling absolute import from netrc import netrc, NetrcParseError

looking in the issue below that have similar warning
https://github.com/kennethreitz/requests/issues/2014
could it be that it related to the fact (if I am not wrong) that during the eventlet patching,  requests removed from the sys.path.

from the eventlet docs:
http://web.archive.org/web/20110723123938/http://www.eventlet.net/doc/patching.html#monkeypatching-the-standard-library

eventlet.patcher.import_patched(module_name, *additional_modules, **kw_additional_modules)
Imports a module in a greened manner, so that the module’s use of networking libraries like socket will use Eventlet’s green versions instead. The only required argument is the name of the module to be imported:

import eventlet
httplib2 = eventlet.import_patched('httplib2')
Under the hood, it works by temporarily swapping out the “normal” versions of the libraries in sys.modules for an eventlet.green equivalent. When the import of the to-be-patched module completes, the state of sys.modules is restored. Therefore, if the patched module contains the statement ‘import socket’, import_patched will have it reference eventlet.green.socket. One weakness of this approach is that it doesn’t work for late binding (i.e. imports that happen during runtime). Late binding of imports is fortunately rarely done (it’s slow and against PEP-8), so in most cases import_patched will work just fine.

so I just want to verify the the warning is ok (because looks that the patched version of requests works quite fine)

**Comment by sigmavirus24** [comment]
eventlet shouldn't be affecting the import of netrc. I'm also not certain if eventlet has special case handling for requests. All eventlet should be patching is socket or httplib (or both) as far as I know, so this seems like a bug for eventlet, not us. I don't use eventlet with requests, nor does @Lukasa so neither of us can tell you that this isn't going to break anything (i.e., that the warning is okay). So if you want assurances, you'll need to search elsewhere (e.g., ask a question on StackOverflow and tag it with eventlet so that someone more familiar with eventlet will answer your question).

**Comment by maxkoryukov** [comment]
As mentioned above, the problem is in the `eventlet` library.

Here is an original tip (by @temoto) how to solve the problem: https://github.com/eventlet/eventlet/issues/208#issuecomment-76978478

And this is my workaround:

```python
from eventlet import import_patched
requests = import_patched('requests.__init__')
```

## see also

* https://github.com/requests/requests/issues/2469
* https://github.com/requests/requests/issues/2014
