### ISSUE TITLE
requests can't detect the right charset

### ISSUE THREAD

**Issue by gengjiawen** [kennethreitz/requests#2473]
I write some code in python 3:
```
url = "http://www.kanunu8.com/book/3981/42775.html"
r = requests.get(url)
print(r.encoding)
print(r.text)
```

from the html source code,it clearly state it's charset is gbk,but r.encoding is "ISO-8859-1".
BTW,I can get the right html from urllib.request.

**Comment by Lukasa** [comment]
Hi there!

This is a well known requests behaviour that is clearly documented. I answered this in a previous GitHub issue [here](https://github.com/kennethreitz/requests/issues/2122#issuecomment-48448778): please consult that answer.

**Comment by gengjiawen** [comment]
But the function`requests.utils.get_encodings_from_content` raise a exception

```
Traceback (most recent call last):
  File "D:/Developer/Python/PythonEx/Http/Crawler/requests_with_coding.py", line 5, in <module>
    codings = get_encodings_from_content(r.content)
  File "C:\Python34\lib\site-packages\requests\utils.py", line 304, in get_encodings_from_content
    pragma_re.findall(content) +
TypeError: can't use a string pattern on a bytes-like object
```

**Comment by Lukasa** [comment]
We plan to remove `get_encodings_from_content` in requests 3.0, because we don't think we should have any code to support reading HTML at all. We are _not_ an HTML library, we're a HTTP library, and we don't want to introspect request bodies at all if we can help it.

The code for it is extremely simple, you can easily bring it into your own project. Find it [here](https://github.com/kennethreitz/requests/blob/master/requests/utils.py#L288).

**Comment by gengjiawen** [comment]
I got it, thanks a lot :)

**Comment by gengjiawen** [comment]
For anyone may see this, you can use Beautifulsoup to get the desired html:
just use: `soup = BeautifulSoup(r.content)`
