### ISSUE TITLE
Use Requests in Pycharm has a ImportError

### ISSUE THREAD

**Issue by viweei** [kennethreitz/requests#2475]
### Error: AttributeError: 'module' object has no attribute 'get'
When I use Pycharm Requests, error: "AttributeError: 'module' object has no attribute 'get'"
I modified file "requests\packages\urllib3\connection.py" in the 8-11 row
```python
try: # Python 3
     from http.client import HTTPConnection as _HTTPConnection, HTTPException
except ImportError:
     from httplib import HTTPConnection as _HTTPConnection, HTTPException
```
To:
```python
py   = sys.version_info
if py >= (3, 0, 0):
    from http.client import HTTPConnection as _HTTPConnection, HTTPException
else:
    from httplib import HTTPConnection as _HTTPConnection, HTTPException
```
It worked.

### Environment：
Pycharm 4.04
Python 2.75

**Comment by Lukasa** [comment]
What is PyCharm doing here? Because it seems to be totally confused.

This is a really common pattern, and it's considered good style: it's better to test for features than to do strict version checks wherever possible. The follow-on is: there's never access of an attribute called 'get' from the module you changed. So again, it feels like PyCharm is getting this wrong.

**Comment by sigmavirus24** [comment]
No response in almost a month. Closing as inactive.
