### ISSUE TITLE
Cookies + proxy

### ISSUE THREAD

**Issue by ttomoday** [kennethreitz/requests#2498]
I'm sending requests to some site using using proxy servers for each request another proxy.
I'm not a pro in this sphere, so I'm interested in such thing:
- are cookies generated each time while i'm sending requests?
- can site (to which i'm sending request) identify my computer based on cookies or another factor and to find out that this request and other ones where made especially from my computer?

**Comment by Lukasa** [comment]
1. It depends. If you aren't using a [Session object](http://docs.python-requests.org/en/latest/user/advanced/#session-objects), then yes, cookies are generated each time because we have nowhere to store them. If you _are_ using a Session object, then you should re-use the cookies, because cookies are tied to the origin server, not the individual connection.
2. Yes. That's exactly what cookies are for.

**Comment by Lukasa** [comment]
@ttomoday By the way, while I did answer your questions, please note that this issue tracker is a place for reporting bugs and discussing improvements, not for general questions about library usage or about HTTP more widely. I recommend using Stack Overflow to ask further questions of that nature. =)

**Comment by vtenq** [comment]
okay, thanks for your answers
