### ISSUE TITLE
Passing multiple certs for CA validation

### ISSUE THREAD

**Issue by nanonyme** [kennethreitz/requests#2499]
It would be nice that requests allowed passing multiple certs for CA validation. It might be for reason or another be unfeasible to merge CA certs into one bundle. In comparison stdlib ssl you can run load_verify_locations arbitrary amount of times to load more certificate locations.

**Comment by Lukasa** [comment]
Requests absolutely does allow that, you just need to concatenate your various certs together into one file that you then pass to `verify`.

**Comment by nanonyme** [comment]
Yeah, I was meaning without concatenating your certs together in one file. That's specifically what load_verify_locations called multiple times avoids. That's especially useful on Windows since the system certificate store is not a file but a binary storage accessed through an API.

**Comment by Lukasa** [comment]
@nanonyme Currently we can't achieve this: we just don't have the primitives. At the very least we would need shazow/urllib3#507 to get merged before this is even possible.

Additionally, the stdlib SSL module only allows this for some versions: specifically, those with SSLContext objects. That limits it to 2.7.9 and later, which is problematic.

Finally, of course, this doesn't solve the Windows problem since Windows users can't point OpenSSL at a file _period_, they need another solution.

Altogether, I think this is just too niche a request to satisfy at the moment. It seems like it would make life easier for a tiny minority of users, but that minority would be just as well served by a merge of sshazow/urllib3#507 and then playing with SSLContext objects.

Thanks for the suggestion, though! Please keep them coming. =)
