### ISSUE TITLE
Redirect doesn't pass all parameters

### ISSUE THREAD

**Issue by pvanderlinden** [kennethreitz/requests#2503]
When you write your own adapter which takes other parameters then the default adapter, resolve_redirects only pass in the parameters which the default adapter takes, this is different from the first request as it passes all parameters to the send function.

**Comment by Lukasa** [comment]
Good spot, we should aim to fix that. Not sure where we'll store them though.

**Comment by pvanderlinden** [comment]
Requests currently keeps all those parameters seperatly (just in a local variables I think), instead of getting them from **kwargs invidually pass them whole kwargs to the redirect resolver? I might raise a PR for this tomorrow if I come around it.

**Comment by Lukasa** [comment]
I think having a PR to talk around would be good. I'm kinda scattered today, so it'll be nice to have something concrete to look at. =)

**Comment by sigmavirus24** [comment]
So I'm mildly -0.5 on this. In practice we've seen that 99.9% of the users are satisfied by how `resolve_redirects` passes parameters. So `resolve_redirects` takes exactly the parameters it needs to know about.

Having a PR is still nice to have, but I'll caution you against an immediate no-go: Do not replace the existing optional parameters to `resolve_redirects` with `**kwargs` because that breaks a public API that previously accepted positional arguments.
