### ISSUE TITLE
expose request start time

### ISSUE THREAD

**Issue by est** [kennethreitz/requests#2625]
When implementing time based throttle mechanism, the start of request time is quite useful, please consider expose it as instance property, so we don't need to wrap requests in a multiple `time.utctime()` calls. It's a waste of syscall and duplicated code.

https://github.com/kennethreitz/requests/blob/master/requests/sessions.py#L570

**Comment by sigmavirus24** [comment]
I don't think we're going to expose it. We weren't keen to expose the `elapsed` attribute in the first place. We're not going to add yet another attribute, especially one we've never had a request for before. `elapsed` was only necessary because the hooks provided by requests were severely trimmed in 1.0.

**Comment by sigmavirus24** [comment]
If no one comments in the next 6 days, I'm going to close this.

**Comment by est** [comment]
I am ok with closing this,  as long as `elapsed` will be obsolete

**Comment by sigmavirus24** [comment]
## Why do you want a widely used feature to be removed? 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by est** [comment]
@sigmavirus24 Pardon my poor English, but how could  `elapsed` be widely used and you weren't keen to expose it?

My rationale is like this, since `elapsed` is widely used, and it involves a system call to get start request time, so it'd better to directly expose the start request time as a property directly, so other developers can make more use of this measure without wrapping yet another get current time system calls. As you can see people use `requests` often involve with time based constraints and there would be a ton duplicated code.

**Comment by sigmavirus24** [comment]
> how could elapsed be widely used and you weren't keen to expose it?

It wasn't widely used before we added it. We were hesitant to add the attribute in the first place but (like most things that are added to public APIs) people use it because it's there. It's widely used now and it's not something we're going to remove.

There's two things to consider though:
1. Requests is in a feature freeze at the moment. That means no new additions to the API.
2. You are the first person in several years to ask us to expose this feature. Without a large number of people needing this to be provided by requests, the default answer is "No."

That said, you keep complaining about needing this causing you to make another system call. If you think system calls are inhibiting the performance of your application, I would strongly urge you to do real benchmarking to determine what is the actual cause of performance degradation. If you've already optimized every part of your application and have found that these system calls are causing performance problems that are noticeable, I think you have other problems to solve.

**Comment by est** [comment]
Now I feel stupid since me alone is complaining this.

This must be a bad idea. Sorry for this, I'll see myself out.
