### ISSUE TITLE
Extend "verify" to accept directory argument

### ISSUE THREAD

**Issue by staticglobal** [kennethreitz/requests#2659]
On my systems I exclusively work with collections of CA certificates stored as individual files in a single directory (with appropriate c_rehash symlinks) rather than the large monolithic "CA BUNDLE" file with every cert concatenated inside.  Most *nix distributions provide both.  A directory of certs at /etc/ssl/certs (or similar) as well as the single-large-file.

Monolithic files are probably easiest for most turnkey users who are only going to be connecting to a public server that uses a popular CA.  They can simply download a single file from the internet and point the API at it to get up and running.  However, the directory-based approach is much more manageable for users who need or want to customize their CA selection.  Remove some old untrusted CAs or include a personal or corporate CA.

The openssl and pyopenssl APIs provide for both.  load_verify_locations() accepts both a cafile and capath argument.  You may specify one or the other or both.  However, requests always passes "verify" as the cafile argument, and correctly documents that the input must be a file.  If you try to pass a directory anyway, openssl gives you "SSLError: [Errno 21] Is a directory".

Please expand the definition of the "verify" parameter to also accept directory arguments.  If the argument is a directory, pass it as the capath argument to load_verify_locations(), else continue passing it as cafile.

**Comment by kennethreitz** [comment]
I like this.

**Comment by Lukasa** [comment]
Alright, cool, let's do it.

**Comment by nrjones8** [comment]
I think this is an issue for `urllib3` -- if I understand correctly (and it's very possible I don't!), when `requests` wants to send a request, it [asks for an `adapter`](https://github.com/kennethreitz/requests/blob/master/requests/sessions.py#L567) -- that adapter wraps a `urllib3` connection via `get_connection()`. When that `urllib3` connection has [its socket wrapped](https://github.com/shazow/urllib3/blob/master/urllib3/connection.py#L237), the call to `load_verify_locations` [is made](https://github.com/shazow/urllib3/blob/master/urllib3/util/ssl_.py#L264), but it simply passes the first parameter (which in this case is just a file location). So in order to pass a `capath` argument through, `urllib3`'s `ssl_wrap_socket`'s function would need to change.

**Comment by Lukasa** [comment]
That's entirely correct. However, this is an issue that we want in requests, so for the moment we drive it here. =) An _enhancement_ is required in urllib3, but the exact form that will take is not yet known.

**Comment by nrjones8** [comment]
Ah gotcha, thanks for the clarification!

**Comment by Lukasa** [comment]
Ok, let's get started on this.

**Comment by Lukasa** [comment]
The urllib3 part of this work is in shazow/urllib3#701.

**Comment by Lukasa** [comment]
We can't progress this until urllib3 next pushes a release that contains the appropriate change, so that we can update our bundled dependency. This is on hold until that time.

**Comment by Lukasa** [comment]
See #2858.
