### ISSUE TITLE
Misleading POST documentation

### ISSUE THREAD

**Issue by melbic** [kennethreitz/requests#2686]
The GitHub example at [#more-complicated-post-requests](http://docs.python-requests.org/en/latest/user/quickstart/#more-complicated-post-requests) is very misleading. It would be great to mention the ```json``` parameter. If you want to know what it does, you'll have to navigate all the way through until the ```PreparedRequest``` class.

**Comment by melbic** [comment]
The documentation should be something like:
`:param json: (optional) json data, the passed in object gets serialized to json (json.dumps()) and the content type of the request is set to  'application/json'.`

**Comment by Lukasa** [comment]
@melbic Yeah, sorry, that documentation was written before the `json` parameter was added.

Would you like to propose a pull request with some new wording?

**Comment by sigmavirus24** [comment]
I would rather that pull request be non-destructive. In other words, please do not remove what's already there, merely add. Many people use the "latest" documentation against older versions of requests. We don't really maintain old versions of the documentation so we need the documentation to be somewhat backwards compatible. The section you mention is exactly that. **Adding** information about the `json` parameter is fine, but please note the version for that section so people know "I'm on 2.2.1 installed on Ubuntu 14.04, because the package archives are so wildly out of date, I can't use that feature because it was introduced in 2.4.0 (or whenever we actually introduced it)."
