### ISSUE TITLE
Upgrade to urllib3 1.11 to fix connection pool exhaustion

### ISSUE THREAD

**Issue by rrva** [kennethreitz/requests#2687]
An important fix has been made to urllib3 which fixes http connection pool exhaustion when connections fail:

https://github.com/shazow/urllib3/issues/644

Can you release a new version which uses urllib3 1.11 ?

**Comment by Lukasa** [comment]
We plan to: see #2678.

For future reference, two of the three requests core developers are also urllib3 core developers. urllib3 does not sneakily release software without us noticing. ;)

**Comment by sigmavirus24** [comment]
## I'm not a core developer on urllib3. :-P... Or is Kenneth?

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Lukasa** [comment]
Pfft, sure you are.

**Comment by jmoldow** [comment]
PR #2678 is currently using a checkout of urrlib3 from some commit that is slightly earlier than 1.11. I understand 1.11 wasn't released yet when the PR was first created. But since I don't see any comments on that PR indicating either way, I was wondering: will you be updating the PR to use the released version, or is there a reason the PR is still using the checkout that it's using?

**Comment by Lukasa** [comment]
We will update the PR. =)
