### ISSUE TITLE
Allow to modify query parameters in authentication classes

### ISSUE THREAD

**Issue by thedrow** [kennethreitz/requests#2702]
Some APIs like https://www.virustotal.com/en/documentation/private-api require you to pass the API key in a query parameter which is not possible at the moment because the request is prepared before the authentication class is applied.
Using the following authentication class:
```python
class VirusTotalAuth(auth.AuthBase):
    def __init__(self, api_key):
        self.api_key = api_key

    def __call__(self, r):
        r.params['apikey'] = self.api_key

        return r
```

Produces this error:
```
AttributeError: 'PreparedRequest' object has no attribute 'params'
```

Which makes sense because you can't change a request's parameters after it has been prepared.

**Comment by sigmavirus24** [comment]
> Which makes sense because you can't change a request's parameters after it has been prepared.

You can change a request's parameters. The current way to do so (since you're actually receiving a `PreparedRequest` instance) is to:
1. Parse the url
2. Change the parameters
3. Unparse the url
4. Set the `url` attribute

This is well documented in other similar issues.

That said, I would posit that an Authentication Handler for this purpose is not ideal. Once you've authenticated, it makes more sense to add the API key to a `Session`'s `params` dictionary so it is added to every request there-after automatically.
