### ISSUE TITLE
FR: Ability to enable raise_for_status for all requests on a Session object

### ISSUE THREAD

**Issue by fgimian** [kennethreitz/requests#2711]
Hey there,

Firstly, I absolutely adore requests, it's the reference library for Python and would like to thank you greatly for creating it.

Today I found the little utility function raise_for_status which I think is very useful, but I think it's a little tedious having to call this for each request if this is the way you prefer to work.

Would you please consider a way to allow for this to be run automatically each time a request is made?  I was thinking you could have a kwarg to Session which enables it for all requests, and possibly a kwarg for requests.get and so forth?

Thanks again! :smile: 
Fotis

**Comment by Lukasa** [comment]
Sorry @fgimian, it looks like this got lost!

Generally I don't believe automating a single function call is a particularly good idea. The cost of doing that is that it makes it hard to tell from reading code exactly what exceptions a given call into Requests might raise, because they depend on the `Session` object elsewhere in the code.

Given that the only advantage is to save you a single function call, I think this is probably not worthwhile. Sorry!

**Comment by fgimian** [comment]
Thanks for your reply @Lukasa, I understand where you're coming from.  Really appreciate you considering my idea :smile:
