### ISSUE TITLE
Log in to Wikipedia not working

### ISSUE THREAD

**Issue by aewhatley** [kennethreitz/requests#2760]
I'm trying to log into Wikipedia using the following code:

import requests

s = requests.Session()
url = 'https://en.wikipedia.org/w/index.php?title=Special:UserLogin&returnto=Main+Page'
values = {'wpName' : '.....',
        'wpPassword' : '.....'}
s.get(url)
req = s.post(url, values)
print(req.cookies)
print(req.url)

However, it does not work. The req.url is the same as the login page (https://en.wikipedia.org/w/index.php?title=Special:UserLogin&returnto=Main+Page), and the cookie jar is empty. Does the MediaWiki software block the requests module, or am I doing something wrong?

**Comment by Lukasa** [comment]
Your URL is wrong.

Please open the page in your browser and enable your browser developer tools, and then try the login yourself. You'll note that the POST target is actually `https://en.wikipedia.org/w/index.php?title=Special:UserLogin&action=submitlogin&type=login&returnto=Main+Page`, not the URL you used (which is missing the `action=submitlogin&type=login` portions.

Additionally, your form is missing some values. My test (username 'test', password 'testpass') ends up sending the following values:

```
wpName:test
wpPassword:testpass
wpLoginAttempt:Log in
wpLoginToken:3cc5dc5e021f5790ad020deced537681
wpForceHttps:1
wpFromhttp:
```

The loginToken, in particular, is something you'll need to scrape out of the page. I'm not going to provide instructions here because this is a bug tracker, not a generalised help forum: if you need more specific advice I'd recommend using [StackOverflow](https://stackoverflow.com/).
