### ISSUE TITLE
Problem with `json` parameter in POST for requests 2.8.0

### ISSUE THREAD

**Issue by asieira** [kennethreitz/requests#2819]
The following code works in requests 2.7.0 but raises an assertion error in 2.8.0:
```
import requests

session = requests.session()
session.headers.update({'x-api-key': 'blah', "Accept-Encoding": "gzip, deflate",
                              "User-Agent": "magnet-sdk-python"})
session.verify = True
req = requests.Request(method='POST', url='https://portal.niddel.com/api/v1-beta/alerts', params=None, json={'a': 1, 'b': 2})
req = session.prepare_request(req)
assert req.body
```

Since I provided neither `files` not `body`, I would have expected `json` to work.

In case you need this info to reproduce the issue, all tests were performed on a Mac OS X with Python 2.7.10 (installed using homebrew).

**Comment by Lukasa** [comment]
@asieira Thanks for this! This is a duplicate of #2813, and should be resolved in 2.8.1.

**Comment by asieira** [comment]
:+1:

**Comment by paulinhomacedo** [comment]
Bom dia Pessoal, estou com o um projeto na empresa onde devo se comunicar com o serviço do governo e estou patinando para se autenticar no mesmo onde pede para enviar o certificado encapsulado em uma keystore como demostra o link abaixo:

https://val.portalunico.siscomex.gov.br/docs/api/

Já tentei de diversas formas, mas sempre me retorna o erro:

HTTPSConnectionPool(host='val.portalunico.siscomex.gov.br', port=443): Max retries exceeded with url: /portal/api/autenticar (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))

Fiz o teste pelo Postman tambem e esta se comunicando corretamente, ate copiei o código gerado por ele, só que o mesmo não gera o parte do codigo do handshake:

O certificado esta VALIDO, e é utilizado no ambiente de produção, ou seja não tem nenhum problema com o mesmo.

import http.client 

conn = http.client.HTTPSConnection("portalunico.siscomex.gov.br") 

headers = {'role-type': "IMPEXP"} 

try:

    conn.request("POST", "/portal/api/autenticar", headers=headers) 

    res = conn.getresponse()

    data = res.read()

    print(data.decode("utf-8"))

except Exception as erro:

    print('Erro:'+str(erro))  

 

Segue abaixo o codigo que tenho:

# coding:utf-8

#!/usr/bin/env python 

from OpenSSL import crypto

from requests_pkcs12 import post

import requests_pkcs12 

url = "https://val.portalunico.siscomex.gov.br/portal/api/autenticar"

certificado = "certificado.p12"

 

#certif = pkcs12_filename = certificado

#key    =  pkcs12_password = '123456'

 

#certificado = (pkcs12_filename=certificado,pkcs12_password='123456') 

header = {"Content-Type": "application/json",                          

          "Role-Type": "IMPEXP"} 

try:

    post(url,headers=header,proxies =proxy, pkcs12_filename=certificado,pkcs12_password='123456')   

except Exception as e:   

    print('Erro:'+str(e))

 

Se alguém souber de como eu realizar essa autenticação ficaria muito grato. 

Obrigado ....
