### ISSUE TITLE
urlib3.HTTPResponse.stream would confuse gzip content originally not encoded utf8

### ISSUE THREAD

**Issue by yupbank** [kennethreitz/requests#2874]
Hi, i was using requests for get gziped web page which originally encoded in gbk.

as requests would try their best decoding gziped pages but as originally not by utf-8 would make the result weried and hard to debug :(

**Comment by Lukasa** [comment]
@yupbank Sorry, I didn't fully understand this message. Can you post some code that demonstrates the problem?

**Comment by yupbank** [comment]
basically 
i figured the correct way:

```
zlib.decompress(requests.get('http://zhongyanghuachengzs.fang.com/', stream=True).raw.read(),  
         zlib.MAX_WBITS|32).decode('gbk'))
```

as the page is encoded in gbk and  gziped.

also due to the fact that requests would auto decompress gzip, this would give weird results.

```
requests.get('http://zhongyanghuachengzs.fang.com/')
```

**Comment by Lukasa** [comment]
I don't believe this is a urllib3 bug: nothing unexpected is happening here.

As you've correctly spotted, requests is transparently decompressing the gzip. This is working perfectly, nothing unexpected is happening. However, I suspect you're then using `response.text`, which is trying to decode the response body. Because there's no header explaining what encoding was used, requests falls back on the spec which claims that text/html should be served in ISO-8859-1. This is wrong for this page, and so it breaks the rendering.

All you need to do is:

```
requests.get('http://zhongyanghuachengzs.fang.com/').content.decode('gbk')
```

That'll work perfectly. =)

**Comment by yupbank** [comment]
thanks a lot, i should follow the document carefully :)
