### ISSUE TITLE
response.request.headers does not contain the Hosts Header

### ISSUE THREAD

**Issue by nucc1** [kennethreitz/requests#2905]
if you iterate over the headers of the response objects request, you do not get the complete set. The Host Header is missing. 

``` python
sending_headers = {"Accept-Encoding": "identity"}
method = "GET"
url = "http://192.168.205.65/poster.php"
resp = requests.request(method, url, headers = sending_headers)
rh = resp.request.headers #original request might be lost in redirects?

for header in rh:
    print("%s: %s" % (header, rh[header]))
```

Observe the output:
```
Accept-Encoding: identity
Accept: */*
User-Agent: python-requests/2.8.1
Connection: keep-alive
```

However, on the wire, you will see:
```
GET /poster.php HTTP/1.1
Host: 192.168.205.65
Accept-Encoding: identity
User-Agent: python-requests/2.8.1
Connection: keep-alive
Accept: */*
```

**Comment by Lukasa** [comment]
This is because, ordinarily, requests does not set the `Host` header at all: `httplib` does. We generally don't get in the way of that because httplib wants to set it.

In general, requests does not (and indeed cannot) claim that the headers variables (on both requests and responses) represent the full set of headers that were on the wire. Some or all may be added or removed by lower layers of the stack, and requests cannot control that.
