### ISSUE TITLE
Support arguments whose values are None

### ISSUE THREAD

**Issue by rohithpr** [kennethreitz/requests#2907]
The docs say: `Note that any dictionary key whose value is None will not be added to the URL’s query string.`

Is there a chance that this could be controlled by the user to include None values as well? Perhaps with the help of a flag.

**Comment by Lukasa** [comment]
@rohithpr What would a `None` value be turned into?

**Comment by rohithpr** [comment]
@Lukasa - `null` perhaps?

```
>>> json.dumps({'val':None})
'{"val": null}'
```

**Comment by Lukasa** [comment]
@rohithpr The only place we turn dictionaries into JSON is the `json=` keyword argument, and that is not put into the URL's query string. Query strings in URLs are not JSON, they're urlencoded key-value pairs.

**Comment by Lukasa** [comment]
I should ask: what is your _actual_ problem? What are you trying to achieve that you believe you cannot with requests?

**Comment by rohithpr** [comment]
No, I didn't mean to say that it should follow JSON. I just said that None could be converted to null along the lines of JSON.

**Comment by Lukasa** [comment]
So again, I'm inclined to ask about what exactly you're trying to do. My reading of this issue is that you want the `None` value turned into _something_, but you don't care what it is. That's an unusual request: ordinarily I'd expect someone to have a specific service they're talking to that makes it natural to represent the data in a certain way (namely, to have `None` in there somewhere).

What's the reasoning here?

**Comment by rohithpr** [comment]
I'd like to pass a `null` value for some arguments in a PUT (or any other) request.

```
data = { 'p1': 'hello', 'p2': None}
requests.put(url, data)
```

On doing this, the server gets only 'p1' and not 'p2'.

In the project that I'm working on key:null is used to delete a key from a record while updating the database. I don't have control over the server side code and I'm unable to pass null values using requests. (The ORM used on the server side is Vogels for DynamoDB)

**Comment by sigmavirus24** [comment]
If you want `null` that's something you should control by looping over the parameters you are passing and swapping `None` for `'null'`. This is not something requests is going to change.

``` py
def convert_None_to_null(params):
    new_params = {}
    for (key, value) in params.items():
        if value is None:
            value = 'null'
        new_params[key] = value
    return new_params
```

**Comment by Lukasa** [comment]
I see.

So, the use of `null` in this fashion is specific to your server: it is not _generally_ true about the URL query string. Requests tries to restrict itself to the subset of behaviour that is universally understood in the query string. Implementation-specific variances have to handle that themselves: otherwise, requests will grow a million different feature flags that subtly change its behaviour in all sorts of weird ways. This kind of combinatorial expansion of the API and the possible configurations of requests would make it a nightmare to use, maintain, and debug.

@sigmavirus24 has provided you a code snippet that should do what you're looking for (with some small edits). I hope you find that helpful!

**Comment by rohithpr** [comment]
@Lukasa @sigmavirus24 - Thanks! :)
