### ISSUE TITLE
Connections not recycled when stream=True and body not consumed

### ISSUE THREAD

**Issue by mirosval** [kennethreitz/requests#2924]
Calling `response.close()` does not seem to release the connection back to the pool. I'm only using the headers or even just `status_code`, so the content doesn't get downloaded, I call `response.close()` but then the next request opens up a new connection. 

Is there a reason for this? It seems that the documentation is insufficient at the very least, if this is intended behavior.

**Comment by Lukasa** [comment]
If you don't consume all the data from the underlying connection, the connection actually _cannot_ be re-used. This is because requests has no way of signalling to the operating system that it doesn't care about the data already received except by closing the socket and throwing the connection away.

Documenting this limitation is possible, but given that it's a reality of how TCP connections function it's hard to justify I think.
