### ISSUE TITLE
Add response.closed attribute

### ISSUE THREAD

**Issue by vitorbaptista** [kennethreitz/requests#2940]
I'm able to explictly close a response by calling `response.close()`, but as far as I could see, the only way to check if the response is closed or not is calling `response.raw.closed`. This feels like violating Demeter's Law, so I would suggest adding a `response.closed` attribute.

If you agree, I'd be happy to send a pull request with this change.

**Comment by Lukasa** [comment]
@vitorbaptista Out of interest, why do you care if the response object is closed?

**Comment by vitorbaptista** [comment]
I have a class that internally uses requests, but not through contexts (I have to keep the response around for a while, so I can't use contexts). I want to write a test to ensure that the response is closed after the object is destroyed.

Right now, I'm testing it using `response.raw.closed`, which is OK, but as `response.close()` already exists, it seems like `response.closed` should exist as well.

**Comment by Lukasa** [comment]
So, the reason I asked is that `response.close()` doesn't do what you think it does. Because we pool our connections, the method doesn't necessarily close anything at all: it just returns the socket connection (that may or may not still be open) to the connection pool.

It should be totally safe to repeatedly call `response.close()`: the method should be idempotent. For that reason, a `closed()` property isn't really necessary: just call `close` instead of checking!

**Comment by vitorbaptista** [comment]
hmmm, interesting... but still, I need to check in the tests that the response was closed. `response.raw.closed` isn't ideal, but works fine. I could also use mocking to check that `response.close()` was called, but using `response.raw.closed` is better IMHO.

In the end, I created this issue just because it was a bit surprising for `response` to have `close()` but not `closed`. It looked like an easy change. There're other easy ways to do what I wanted to do, though, so it doesn't add much.

I'll close this issue for now. If you think this change is worthwhile, please reopen and I'd be happy to write a pull request solving it.

Thanks for your help :+1:
