### ISSUE TITLE
API feature - POST request to HTML element by id

### ISSUE THREAD

**Issue by aewhatley** [kennethreitz/requests#2956]
Right now, the requests.post() function only appears to send post requests to HTML elements by their name. Are there any plans of creating something like a requests.post_to_name() and requests.post_to_id(), so that the user can make post requests to HTML elements via their id instead, similar to the API used in Splinter for accessing HTML elements?

**Comment by sigmavirus24** [comment]
@aewhatley requests is an _HTTP_ client and has nothing to do with _HTML_. POST requests are made to URLs, not HTML elements. As such, we would not be adding any such methods because they wouldn't make sense as part of our API.

Thanks for the suggestion but I think you're a little confused about how requests works.
