### ISSUE TITLE
URL-encoded boolean parameter passed as ?foo=True instead of ?foo=1

### ISSUE THREAD

**Issue by FlyingLotus1983** [kennethreitz/requests#2999]
When encoding a boolean into a URL encoded parameter:

```
payload = {'foo': True}
resp = requests.post(path, params=payload)
```

Requests currently generates: `?foo=True` .. I would expect the boolean to be encoded as a 1 or 0, e.g. `?foo=1` , as some clients may not understand `True` as a boolean. 

I did some google searching, and I am not even sure if there are rules for how a boolean should be encoded, I didn't find any specific guidelines, just that a lot of URL encoding libraries seem to always encode booleans as 1's and 0's.

Apologies if this is known and/or expected behavior.  I'm not a web guru by any means, but at the least, Requests does seem to be handling it differently than other libraries I've used in the past.

**Comment by Lukasa** [comment]
There are no rules for how to encode Boolean types, because urlencoding is performed on strings, not on typed objects. For that reason, Reuests coerces all objects passed to the urlencoding logic to strings (except for `None`, which it handles specially).

This is not considered a bug by the requests team: while it can be surprising if you come from a non-requests background, I'd argue that in aggregate our behaviour is far less surprising than converting objects into entirely different representations.

**Comment by kennethreitz** [comment]
@FlyingLotus1983 if you want a `1` there, you should provide a `1` :)
