### ISSUE TITLE
"Request.hooks" and "Session.hooks" merged inappropriately.

### ISSUE THREAD

**Issue by er1iang** [kennethreitz/requests#3016]
Both `Session` and `Request` have attribute `hooks`. The hook function list execute sequentially. In this situation, `Session.hooks` executed for every request and `Request.hooks` executed for a specifical request.

But in fact, `Session.hooks` were replaced with `Request.hooks` when code ran into
`merge_setting`:

```Python
    merged_setting = dict_class(to_key_val_list(session_setting))
    merged_setting.update(to_key_val_list(request_setting))
```

**Comment by Lukasa** [comment]
@evilerliang Do the requests docs guarantee that `Session.hooks` will not be replaced by `Request.hooks`? In general, things declared for specific requests _override_ the things declared on the `Session`, rather than _supplementing_ them.

**Comment by elonzh** [comment]
I reviewed the doc, thk.

> Any dictionaries that you pass to a request method will be merged with the session-level values that are set. The method-level parameters override session parameters.
> 
> Note, however, that method-level parameters will not be persisted across requests, even if using a session.

**Comment by kennethreitz** [comment]
Hmmm, we should consider appending any additional hooks provided by a method-level request, instead of overwriting. 

_e.g._

```
# session has a 'response' hook defined; additionally provided hooks get *merged*.
session.get(..., hooks={'respose': ...}

# session has a 'response' hook defined; all 'response' hooks removed.
session.get(..., hooks={'respose': None}
```

This is tricky, because in this scenario there is no way to specify nullifying the session hooks while simultaneously providing your own for the request. I believe this must be why I implemented it the way it is today, and justifies the current behavior as _correct_. 

---

**Random hooks thoughts:** Not sure if it's worth changing any hooks behavior at this point, since hooks were at one point in time much more powerful (since there were more of them). Now they're really just used for internal stuff, e.g. custom authentication providers. 

I don't actually perceive hooks, in their current state, being used much by users, and as such could potentially be removed from the documentation, to further their internal-ness. Or, possibly, they could be moved to a new section of the documentation for people extending requests.

Just random thoughts.

**Comment by elonzh** [comment]
That's fine. I changed the hook behavior in my package. Thanks again, you help me a lot.
