### ISSUE TITLE
requests can't make a request to the server it's running on

### ISSUE THREAD

**Issue by rajrsingh** [kennethreitz/requests#3027]
Here's a test case that never returns a response. Shouldn't this work?

```python
import requests
from flask import Flask
app = Flask(__name__)

@app.route('/')
def Welcome():
    return "Testing requests module's ability to call the service in which it's running"

@app.route('/test')
def TestRequest(): 
    resp = requests.get('http://0.0.0.0:5004')
    print('Response from TestRequest: '+r.text)

if __name__ == "__main__":
	app.run(host='0.0.0.0', port=5004, debug=True)
```

**Comment by Lukasa** [comment]
Flask's debug server cannot handle multiple requests at once. Run Flask behind a proper WSGI server and you'll be fine. =)

**Comment by isc-rsingh** [comment]
Thanks for the tip @Lukasa. I'm a newbie when it comes to Python web serving. Been struggling getting Apache WSGI module + Flask on OS X el capitan all day. First it was SIP (system integrity protection) and now it's getting Apache/OS X python to recognize my anaconda python modules. This whole process is extremely unpleasant. Do you happen to know what "proper WSGI server" folks tend to use?

**Comment by sigmavirus24** [comment]
@rajrsingh there are too many to list, but here are a few:
- Apache+mod_wsgi
- gunicorn
- uwsgi
- twisted

**Comment by kennethreitz** [comment]
Use gunicorn. :)

**Comment by isc-rsingh** [comment]
Thanks for the info. I'll put some of my research here for future Googlers. 
1. Getting mod_wsgi installed on OS X El Capitan with SIP is annoying. This is the best resource on that: https://github.com/GrahamDumpleton/mod_wsgi/issues/98. I ended up using the technique of disabling SIP, then installing mod_wsgi. 
2. Then my problem was either getting Python modules (like pandas and Flask) installed in the system Python, which Apache insists on using, or figuring out how to get Apache to recognize my Anaconda Python install. I gave up at this stage because...
3. I found a way to get Flask to be multi-threaded here: http://stackoverflow.com/questions/14672753/handling-multiple-requests-in-flask so I can continue my dev work on the laptop with no "real" WSGI server.
4. Next step is to try out gunicorn and get it all running on my eventual production environment on http://bluemix.net.

**Comment by isc-rsingh** [comment]
So the strict answer to the question is nothing is wrong with requests, I just needed to add the `Threaded=true` parameter to the test server.

``` python
import requests
from flask import Flask
app = Flask(__name__)

@app.route('/')
def Welcome():
    return "Testing requests module's ability to call the service in which it's running"

@app.route('/test')
def TestRequest(): 
    resp = requests.get('http://0.0.0.0:5004')
    print('Response from TestRequest: '+resp.text)

if __name__ == "__main__":
    app.run(host='0.0.0.0', port=5004, Threaded=True, debug=True)
```
