### ISSUE TITLE
"in" operation on resp.cookies should not raise CookieConflictError

### ISSUE THREAD

**Issue by trilogysci** [kennethreitz/requests#3028]
Hosts which have the same cookie define for multiple domains should not raise 
"CookieConflictError: There are multiple cookies with name,"  when performing "in" 
 It should short cut and return True immediately when found.

**Comment by Lukasa** [comment]
So the problem here is that the default implementation of `collections.Mapping.__contains__` calls in to `__getitem__`, which for the `RequestsCookieJar` requires that there be no duplicate. In this instance, we probably get the most bang for our buck by just overriding `__contains__` to call the parent implementation, and then catch `CookieConflictError` and return `True` in that instance.

I'm marking this as contributor friendly because the fix is fairly easy, and it'd be a good one for someone to pick up as a first open source change.

**Comment by davidsoncasey** [comment]
I've been using requests for a while and thinking I'd contribute, so I might take a shot at this.

**Comment by kennethreitz** [comment]
@davidsoncasey Awesome!

**Comment by jamalmoir** [comment]
I'd like to give this one a go if that's OK.

Cheers.
