### ISSUE TITLE
Response read hangs

### ISSUE THREAD

**Issue by medecau** [kennethreitz/requests#3068]
python 2.7.11
requests installed from pip and up-to-date

URL -> 'http://archive.mid.ru/bdomp/zu_r.nsf/strawebeng!OpenView'

GET request hangs at read time.
I tried to use `stream=True` and then read from `response.raw` and it works. But doesn't finish on normal usage.

I looked at the headers and the `Content-Length` is duplicated.
When I try to read it from `response.headers['Content-Length']` I find a single string: `'133172, 133172'`.
The length is correct otherwise.

I am not entirely sure of what's causing this but my guess is that requests is getting confused by the duplicate header.

_thanks for everything_

**Comment by Lukasa** [comment]
> I tried to use `stream=True` and then read from `response.raw` and it works.

When you did this read, did you just do `read()`, or did you provide a length to the `read()` call?

So, the server is getting this wrong. It is strictly forbidden to send multiple content-length headers, and generally speaking I oppose having code to defend against idiot servers doing things wrong. In this specific instance, however, we have another very similar problem with servers sending duplicate `Location` headers, so I wouldn't be opposed to us providing fixes for both at once, as the fix is basically the same.

**Comment by medecau** [comment]
Yes, I provided the value I get from the duplicate `Conten-Length` header.

**Comment by Lukasa** [comment]
@medecau Yeah, so you'll almost certainly find that if you call `read()` with no arguments (which is what requests normally does), that hangs the same way that requests does. This is because httplib controls the HTTP framing and is presumably confused about what the actual content-length is.

Strictly speaking the best way to fix this would be to raise a bug against httplib, though the _actual_ best fix is to tell the server to sort itself out.

**Comment by sigmavirus24** [comment]
Since this is strictly not something we can fix in requests (or urllib3) I think we should close this. Thoughts @Lukasa ?

**Comment by Lukasa** [comment]
I think we technically _can_ fix it in urllib3/requests, but doing it is pretty invasive. I'd like to approach getting it fixed in httplib first so at least python-dev can say we're lunatics.
