### ISSUE TITLE
allow certs.where to return a file like object

### ISSUE THREAD

**Issue by cburroughs** [kennethreitz/requests#3071]
Currently `certs.where` expects a file name that is then passed along and eventually opened.  This means it is up to the caller to deal with eggs, wheels, install locations, zip_safe vs not etc, to eventually figure out where something is going to end up on the file system..  None of these issues are particularly fun.  Instead of certs.where could return a file like object and a custom implantation could be as simple as `StringIO.StringIO(pkgutil.get_data(__name__, 'cacert.pem'))`

**Comment by Lukasa** [comment]
Unfortunately, `certs.where` cannot return a file-like object: due to several limitations in the way OpenSSL's APIs behave across versions of Python the lowest common denominator is that we need to provide a _path on the filesystem_ to OpenSSL.

This makes it impossible for us to do that. Sorry, it's otherwise a good idea!
