### ISSUE TITLE
In requests.get(), params are in random order

### ISSUE THREAD

**Issue by MrAureliusR** [kennethreitz/requests#3073]
Just wanted to point out that when you pass a dict to requests.get(url, params=dict) the url is encoded with the params in **completely** random order. I didn't think that this mattered, until recently when it bit me. Is there any way to have the params in the same order that the dictionary is in?

**Comment by MrAureliusR** [comment]
Is this an innate problem with Python dictionaries in general?

**Comment by arcan1s** [comment]
did you try `OrderedDict`? Python dict has unordered keys by design

**Comment by MrAureliusR** [comment]
Is that a type or a method?

**Comment by sigmavirus24** [comment]
@arcan1s you don't need an OrderedDict, you only need to provide a list of tuples. And questions should be asked on [StackOverflow](https://stackoverflow.com).

**Comment by MrAureliusR** [comment]
@sigmavirus24  Right, when I realized it was a Python issue, I was going to close the issue. No need to be so .... terse.

**Comment by Lukasa** [comment]
@MrAureliusR The terseness comes from the fact that we get several new issues a day that require that the core maintainers interrupt their days to address. Each bug report costs at least one maintainer a few minutes and a context switch, and may cost more than that if multiple maintainers stop to address it. That's unfortunate when you consider that the majority of the maintainers are unpaid, and all of us are overstretched.

This is doubly problematic for questions. When you opened this issue you were shown this screen:

![screen shot 2016-04-01 at 13 56 23](https://cloud.githubusercontent.com/assets/1382556/14207380/951c6ec6-f811-11e5-9d51-b7842fd8023a.png)

Notice the yellow bar at the top. Had you clicked through and read that link you'd have seen [this document](https://github.com/kennethreitz/requests/blob/master/CONTRIBUTING.md), which contains in its very first section this text:

> The GitHub issue tracker is for _bug reports_ and _feature requests_. Please do not use it to ask questions about how to use Requests. These questions should instead be directed to Stack Overflow. Make sure that your question is tagged with the `python-requests` tag when asking it on Stack Overflow, to ensure that it is answered promptly and accurately.

This is why the interaction was strained: you demonstrated that you had not read that note. Those notes are important to ensure that everyone interacts as efficiently as possible and to ensure that the limited resources of the project are allocated in the most useful way available.

Each issue opened on this bug tracker costs the core team at least 5 minutes of time. We're at issue 3073 right now, meaning that if these had all been _just questions_ we'd have spent nearly _11 days_ just swapping to handle those questions.

I say all of this not to chastise you, but to remind you that open source is a predominantly volunteer operation where the primary resource is time. Asking questions on bug trackers is a common source of wasted time on the part of maintainers, which is why maintainers can be terse when questions are asked in inappropriate forums.

**Comment by sigmavirus24** [comment]
It's triply problematic here because our documentation describes how to handle this exact scenario.

**Comment by MrAureliusR** [comment]
@sigmavirus24 Actually, I DID click through and read that. Thanks for assuming I'm an ignorant ass. I thought, at the time of reporting, that it WAS a Requests bug. I demonstrated that I hadn't read the note... man, I don't even know how to respond to that.
And I know open source is volunteer based, all the more reason NOT to be so terse. If you can't handle the occasional mistake, then maybe you shouldn't complain about spending 5 whole minutes of your life helping someone correct it.

**Comment by kennethreitz** [comment]
Read through the original thread, and I want it to be known that I think @MrAureliusR's submission was perfectly fine. Not every interaction here has to be handled solely by the maintainers (in this instance, a community member was already stepping in to help).

The "be cordial or be on your way" rule applies to maintainers too :) These interactions were fairly cordial, but far from friendly.

**Comment by kennethreitz** [comment]
No further comment needed. Sorry for your bad experience, @MrAureliusR
