### ISSUE TITLE
Improvement to hook response.

### ISSUE THREAD

**Issue by JackDandy** [kennethreitz/requests#3083]
Hello,

It would be nice if the _response_ hook was called even if there is an error during the send() process flow.

Example, if a timeout occurs, the cb is not used and a requests constructed url and query data that can normally be saved via the cb is not available - that is, URL that caused a timeout.

Thanks for your consideration.

**Comment by Lukasa** [comment]
@JackDandy If you pass `stream=True`, then the callback should fire once the response has been received, so that resolves the problem where timeouts are encountered downloading the response data.

If the timeout is encountered while actually downloading the response, we can't call the response hook because we don't have a response to call it with. If you need to intercept that data the best place to do it is likely to be in the HTTPAdapter itself (by overriding the `send` method, which gets a `PreparedRequest` object), or by using the [prepared request flow](http://docs.python-requests.org/en/master/user/advanced/#prepared-requests) which will give you access to those things, also on a `PreparedRequest` object.

Do either of those work for you?

**Comment by sigmavirus24** [comment]
If there is no response to provide to the hook, I'm uncertain what we would call the hook with. I do not think we could safely construct a fake response object just so we can call the response hook (which wouldn't confuse existing response hooks).

You can introspect what requests constructs for the url, query data, etc. by using the prepared request flow.

**Comment by JackDandy** [comment]
The hook is a nice and cheap way to get the constructed URL that is used in the request for logs. To add the prepared request flow seems overkill for URL reporting. A server response has content or none so there is value to add by calling the hook in any outcome.

[edit] If too much hassle to create response objects, then save the built URL/post data in the requests object like _headers_ in order to give a full picture of what requests sent after its pre-processing.

So, yeah, just suggestions.

**Comment by kennethreitz** [comment]
Sounds like `PreparedRequest` is what you want — it was built for exactly this purpose, if I understand you correctly.
