### ISSUE TITLE
Problem in json.dump with headers dictionary

### ISSUE THREAD

**Issue by rodrigozanatta** [kennethreitz/requests#3092]
I really don't know what is happing. I make a `requests.get` and save the returned headers in a dictionary:

```
r = requests.get("http://myurl.com")
my_dic = {'my_header' :  r.headers}
```

When I try to parse my_dic to JSON, I get an error. 

```
with open('arq.txt', 'w') as fp:
    json.dump(my_dic, fp)
```

For no special reason, it fail! I thought there was an illegal character or duplicate key, but no. It only work when I created this function:

```
def fix(old):
    new = {}
    for key, value in old.items():
        new[key] = value
    return new
```

So, I need to do this:

```
r = requests.get("http://myurl.com")
my_dic = {'my_header' : fix(r.headers)}
```

Why? Is this a bug? I am using the python 3.5 and believe all most update libraries.

**Comment by Lukasa** [comment]
So you didn't actually print your error, but the reason it's a problem is that the json module really only accepts dictionaries. `r.headers` is not actually a dictionary:

```
>>> type(r.headers)
<class 'requests.structures.CaseInsensitiveDict'>
```

You can resolve the problem by simply calling `dict()` on it:

``` python
r = requests.get("http://myurl.com")
my_dic = {'my_header' :  dict(r.headers)}
```

**Comment by rodrigozanatta** [comment]
Yeah, now I understand it. But... Why not make it a dictionary? I am new in python and it take hours to understand WHY the JSON was having problem. My first try was some illegal character. Because the error print it like a dictionary. I have the same problem with cookies. 

So I suggest you to make every "like a dictionary" to be a "real dictionary" I can imagine so many problems with it in others frameworks.

**Comment by Lukasa** [comment]
The reason it's not a dictionary is because generally speaking, types defined in Python should not subclass the built-in types. This is because the built-in Python types have various shortcuts in their C implementation that means that they don't call back into Python code, which means they don't see method overrides defined in Python.

For that reason, it is intended that modules use the [collections module's Abstract Base Classes](https://docs.python.org/2/library/collections.html#collections-abstract-base-classes): in our case, [Mutable Mapping](https://docs.python.org/2/library/collections.html#collections.MutableMapping). It is unfortunate that the JSON module doesn't like them, but I believe that's a flaw in the JSON module rather than the data type we've constructed.
