### ISSUE TITLE
requests cannot fetch this website (only in Python 3)

### ISSUE THREAD

**Issue by jribbens** [kennethreitz/requests#3133]
`requests.get("https://www.northwarks.gov.uk/")` hangs.
`urllib.request.urlopen("https://www.northwarks.gov.uk/").read()` works fine.

I am using Python 3.4 and requests 2.9.1.
If I use Python 2.7.10 and requests 2.9.1 then it works fine.

**Comment by Lukasa** [comment]
So, first things first. If we set `allow_redirects=False` and `stream=True`, then the first request works. With anything else set, it hangs. The headers the server sends sends seem to be the problem here. Here's the header block curl is seeing:

```
HTTP/1.1 302 Moved Temporarily
Content-Type: text/html; charset=UTF-8
Location: https://www.northwarks.gov.uk/site/
Server: Microsoft-IIS/8.5
X-Powered-By: ASP.NET
X-FRAME-OPTIONS : SAMEORIGIN
Date: Tue, 26 Apr 2016 17:38:24 GMT
Content-Length: 158
```

Given that header block, Python 3's `http.client` module (which is responsible for header parsing), only parses up to `X-Powered-By`. The reason is that the header after (`X-FRAME_OPTIONS`, weirdly all-capped) is not formatted correctly. RFC 7230 forbids a space between the header name and the colon. This breaks the header parser, which therefore doesn't read the Content-Length header field. That means that requests expects that the connection will be framed by connection close, so it barfs.

The overly-strict header parsing you're seeing here is the fault of the Python standard library. You can raise the issue with them: however, they handled a similar one in [bug 25539](https://bugs.python.org/issue25539) and didn't end up moving forward with a fix in Python.

More realistically, you should contact the server operator and tell them that their server is emitting invalid HTTP. This appears to be a local government server, so it should be possible to get in touch with the operators.

Unfortunately, requests can't do much about this: the standard library is just getting this wrong.

**Comment by jribbens** [comment]
Thanks for the excellent analysis. I will look at the `http.client` issue and I agree that it looks like this is not something requests can fix itself.

**Comment by Lukasa** [comment]
Thanks for the report @jribbens! :sparkles:

**Comment by kennethreitz** [comment]
`X-FRAME-OPTIONS%20` :trollface:
