### ISSUE TITLE
Will requests bundle with future version of python?

### ISSUE THREAD

**Issue by KiYugadgeter** [kennethreitz/requests#3384]
Will requests bundle with future version of python like pathlib? 

I think urllib is not intuitive.
I hope that requests replace urllib as a intuitive high level http request module.

**Comment by Lukasa** [comment]
Thanks for this question! The answer I'm afraid is "no". Requests is security-critical for most users, which means we need to be able to react quickly to security vulnerabilities and ensure that they reach all users. That's not possible if we're in the standard library because of its requirements on backward compatibility and long release cycles.

Additionally, it's never been easier to get a copy of Requests for your Python. Modern Pythons ship with pip, which means that Requests is a simple `pip install requests` away: one small command line. This means that the convenience advantage of bundling with the standard library is pretty minimal.

For this reason, we will not be part of the standard library: we can do better work by being outside it.

**Comment by kennethreitz** [comment]
https://speakerdeck.com/kennethreitz/python-requests-and-the-standard-library

**Comment by kennethreitz** [comment]
The official decision was made for the official Python documentation to recommend Requests, instead. It's now prominent in the urllib documentation.
