### ISSUE TITLE
Automatically executes script in working folder if its name "cgi"

### ISSUE THREAD

**Issue by dan-win** [kennethreitz/requests#3392]
Requests version - 2.10.0
As soon as the working folder folder contains script with name "cgi.py" (it was part of my application), your package automatically executes it. In my case - I fixed that myself by renaming my script. For another users - probability of such case is not zero. (In my case it was about 1 hour of fighting with strange behavior of my application). To reproduce it, it is possible to create 2 simple scripts, e.g.: 

**test.py**:
_import requests
print "Hello from test"_
**cgi.py**:
_print "Hello from CGI!"_

Possible solutions: to reflect such behavior in documentation or to fix it.

P.S. Very nice package, it saved me much more time this lost hour!

**Comment by Lukasa** [comment]
This is not a bug: this is unfortunately the way Python works. Python puts the current working directory at the top of the import namespace, which means that when we try to import standard library modules, if you have a script in the working directory with the same name, we will accidentally get that instead. 

To prevent your script from executing in these circumstances, you will want to use the [`if **name** == '**main**':](http://stackoverflow.com/questions/419163/what-does-if-name-main-do) pattern. That would change this error to either an ImportError or an AttributeError, which are better failure modes. 

Otherwise, try to avoid naming your scripts after stdlib modules. (You'd have similar problems with, for example, naming a script 'urllib.py'.)
