### ISSUE TITLE
How to correctly change the Content of a Response in hook function

### ISSUE THREAD

**Issue by pceBuildMaster** [kennethreitz/requests#3394]
I have registered a `'response'` hook with the Request in the `__call__` method of my subclass of `AuthBase` as I need to check for API errors from my product and massage the output it returns for upstream consumption.

The hook logic is working fine but I have concerns about my approach:

Reading the `Requests API` section and playing around I found setting the Response `_content` with new data works.  But I strongly suspect this is the wrong approach and it will come back to bite me.  The `Requests API` lists `content` but in the hook logic I get the error: `AttributeError: can't set attribute` when I use that one.

Is there a correct way to change the Response content?

**Comment by Lukasa** [comment]
Setting `_content` is fine. That's where we store buffered content. Note that you can't unconditionally read from `_content` to massage in the first place, you do need to use `content`. The reason you can't override `content` is because it's a property that executes a function that does things like lazy loading.
