### ISSUE TITLE
proxy scheme is case-sensitive?

### ISSUE THREAD

**Issue by ryanwy** [kennethreitz/requests#3397]
I'm not sure if this is a bug? please take a look. Thanks.

I use proxy below and  it doesn't work, when I change scheme to lower 'http', it's fine.
**proxy = {'HTTP': '218.26.237.18:3128'} 
url = http://httpbin.org/ip**

I track the source code and don't find anywhere to handle scheme case conversion.

-> requests.get 
-> request 
-> settings = self.merge_environment_settings(
            prep.url, proxies, stream, verify, cert
        )

**from function self.merge_environment_settings, get orderdict object proxies:**
     
**OrderedDict([('HTTP', '118.144.187.254:3128')])**        
 
 -> resp = self.send(prep, **send_kwargs)
 ->   r = adapter.send(request, **kwargs)
 ->  conn = self.get_connection(request.url, proxies)
 ->  proxy = select_proxy(url, proxies) 
def select_proxy(url, proxies):
    proxies = proxies or {}
    urlparts = urlparse(url)
    if urlparts.hostname is None: 
        return proxies.get('all', proxies.get(urlparts.scheme))
    ......

**in function select_proxy, urlparts.scheme = 'http' and proxies.scheme is 'HTTP', so it returns None and the setting proxy is invalid '**

**Comment by Lukasa** [comment]
Yeah, you need to lowercase the scheme in the proxy dictionary. While we could deal with this problem ourselves, it's somewhat problematic to do it because we need to avoid mutating the dictionary that is passed to us. I'll accept a pull request that adds some appropriate lowercasing in the `select_proxy` method (probably by copying the dictionary and lowercasing the keys as we go), but I don't consider this urgent: the documentation always shows people using lowercase keys in the proxy dictionary.

For what it's worth, you should [read that section](http://docs.python-requests.org/en/master/user/advanced/#proxies), as your target URL is not really correctly formatted either: it should also have a scheme.

**Comment by ryanwy** [comment]
Thank you.  so I close this known issue.
