### ISSUE TITLE
Recieving 400 Bad Request on GET-request

### ISSUE THREAD

**Issue by JamesJGoodwin** [kennethreitz/requests#3465]
Hi. I've wrote a code, but i'm getting an error **400 Bad Request**, when sending a GET-request. What i did wrong? 

`{'Host': 'http://keddr.com', 'Keep-Alive': 112, 'User-Agent': 'Mozilla/5.0 (Windows; U; Windows NT 6.1; en-US; rv:1.9.1.8) Gecko/20100223 Firefox/3.5.8 Lunascape/6.1.0.20940 ( .NET CLR 3.5.30729)', 'Accept-Charset': 'ISO-8859-1,utf-8;q=0.7,*;q=0.7', 'Connection': 'keep-alive', 'Referer': 'http://grandsultansaloon.com/plugins/system/plugin_googlemap2_proxy.php?url=EQZMME', 'Cache-Control': 'no-cache'}
<Response [400]>
`
Here goes my Python code:

```python
def httprequest():
	url = sys.argv[1]
	payload = {buildblock(random.randint(50,100)): buildblock(random.randint(50,100))}
	headers = {'User-Agent': random.choice(ua),
		'Cache-Control': 'no-cache',
		'Accept-Charset': 'ISO-8859-1,utf-8;q=0.7,*;q=0.7',
		'Referer': random.choice(ref)+buildblock(random.randint(3,10)),
		'Keep-Alive': random.randint(110,120),
		'Connection': 'keep-alive',
		'Host': url}
	r = requests.get(url, params=payload, headers=headers)
	print(headers)
	print(r)
```

**Comment by Lukasa** [comment]
Well, as a first point your Host header is wrong. Please remove both Host, Header, and Keep-Alive from your header dictionary: Requests will manage those appropriately by itself and will simply ignore anything you set.

**Comment by abriginets** [comment]
Thanks, it helped. And if i'm sending my request, for example, to _example.org_, then in _Host_ header would be a site address? And how can i see all headers my request send?

**Comment by Lukasa** [comment]
@JamesJGoodwin We will populate the Host header for you, don't worry about it. It will always include the host portion of whatever URL you use: if you send to http://example.org, Host will be "example.org".

To see your headers, you can look for `r.request.headers`. That does not show _all_ headers: some automatically added headers (e.g. `Host`) are not provided in that dictionary because the layers below Requests add them.
