### ISSUE TITLE
cannot pass realm parameter to HTTPDigestAuth

### ISSUE THREAD

**Issue by alextorex0** [kennethreitz/requests#3467]
I need to specify a custom realm parameter for HTTPDigestAuth.
It does not seems to be supported.

**Comment by Lukasa** [comment]
When you say you "need to specify a custom realm parameter", what do you believe that parameter will do? The realm is provided by the remote host in the auth challenge.

**Comment by alex-movila** [comment]
I get auth failed if I do not specify it. Besides urllib2 allows to pass this parameter.

**Comment by Lukasa** [comment]
urllib2 allows you to pass it because it associates a specific realm with a given username/password tuple, such that it will only respond for challenges using that specific realm. Requests has a simpler Digest Auth model which does not have realm-specific passwords.

When you say you get auth failed, I'm going to need some more information. What does your code look like for Requests, and what does it look like for urllib2?

**Comment by alex-movila** [comment]
The management interface of Wildfly Jboss is exposed via http/JSON. Basically  it requires to pass realm = 'ManagementRealm' to Digest Auth  otherwise I cannot login as a superuser and get 401. 

The code looks like this:

url = 'http://{host}:{port}/management/host/{host}/server/{server}/core-service/platform-mbean/type/garbage-collector/name/G1_Young_Generation?include-runtime=true'
username = 'admin'
password = 'password'
realm = 'ManagementRealm'

passman = urllib2.HTTPPasswordMgr()  # this creates a password manager
passman.add_password( realm, url, username, password)
auth = urllib2.HTTPDigestAuthHandler( passman)
urlopener = urllib2.build_opener( auth)
request = urllib2.Request(url)
response = urlopener.open(request).read()
d = json.loads( response)
pprint.pprint( d)

**Comment by Lukasa** [comment]
What's your equivalent requests code, please?

**Comment by alex-movila** [comment]
import requests
from requests.auth import HTTPDigestAuth
r = requests.get(url, auth = HTTPDigestAuth('admin', 'password'))
r.request.headers
r.status_code
r.headers['content-type']
pprint.pprint(r.json())

**Comment by Lukasa** [comment]
I assume your passwords here are replacements, and not the actual password? Because they aren't the same.

What does r.history contain?

**Comment by alex-movila** [comment]
r.history contains: <html><head><title>Error</title></head><body>401 - Unauthorized</body></html>
user/password are real but I don't know if they're the defaults after installation

**Comment by Lukasa** [comment]
Ok, can you please print: `r.history[0].headers` please? I'm interested to see what the challenge is.

**Comment by Lukasa** [comment]
BTW, if the username and password are real, why are they different in each example?

**Comment by alex-movila** [comment]
ok fixed now

**Comment by alex-movila** [comment]
{'Date': 'Wed, 03 Aug 2016 11:27:31 GMT', 'Content-Type': 'text/html', 'Connection': 'keep-alive', 'Content-Length': '77', 'WWW-Authenticate': 'Digest realm="ManagementRealm",domain="/management",nonce="v4CCqEhQR2wNMTQ3MDIyMzY1MTEwMoryoyih0IMIqIg2nq4ZP2M=",opaque="00000000000000000000000000000000",algorithm=MD5'}

**Comment by Lukasa** [comment]
So as you can see, the realm is ManagementRealm in the challenge. So at best the realm portion of this is a red herring. We're using the same realm as urllib2 is. The problem has to be elsewhere.

**Comment by sigmavirus24** [comment]
I'm closing this due to about a month of inactivity. If you can provide more information @alextorex0 such that we can continue debugging this, we will happily reopen this.
