### ISSUE TITLE
Add option to specify custom DNS resolver

### ISSUE THREAD

**Issue by yeukhon** [kennethreitz/requests#3470]
My services are running on AWS with some of the applications being external. We would run Nagios check to make sure web applications are still accessible (internally and externally). One challenge I have is to run the check as an external user because our Nagios server is in the VPC so the check is performed over the internal VPC network.

There are many ways to solve my problem, for example recompile libcurl to support resolver option, or run my nagios in another VPC without any knowledge of my external applications, or adopt a proxy server.

However, I found http://stackoverflow.com/questions/22609385/python-requests-library-define-specific-dns. As a Python programmer I like to stick with Python if requests could offer this out of the box.

Is anyone interested and willing to accept an option in requests to specify custom DNS resolver?

**Comment by Lukasa** [comment]
Thanks for this request!

Requests is certainly not going to take a patch use use a custom DNS resolver, partly because we don't want to add flags and options for such low-level functionality, and partly because that functionality is owned entirely by the urllib3 library, which we don't carry patches for.

However, this is the kind of thing that urllib3 would be willing to accept in some form, I suspect, so I recommend you open an issue on that repository.

Thanks again for reaching out!

**Comment by yeukhon** [comment]
@Lukasa  are you saying if urllib3 is updated, then requests could be in the position of having this option?

**Comment by Lukasa** [comment]
No, I'm saying that if urllib3 is updated you can write a [transport adapter](http://docs.python-requests.org/en/master/user/advanced/#transport-adapters) that uses it.
