### ISSUE TITLE
Commit 386382b18caab6a3a8a111fa8e24875dca27b0aa is kicking my ass on Python 3

### ISSUE THREAD

**Issue by alexntt** [kennethreitz/requests#3483]
Hi,

Today our automated builds started failing because 2.11.0 was pulled and 386382b18caab6a3a8a111fa8e24875dca27b0aa causes a request's body to be a bytes object in Python 3 but a str in Python 2.7, which is breaking both my code and https://github.com/seanbrant/requests-wsgi-adapter:

https://gist.github.com/alexntt/b181b562852c6850a83269b7401d3bef

Can this be made a bit more "backwards-compatible"?

Cheers,

Álex

**Comment by Lukasa** [comment]
Bytes and str are the same type. In fact, bytes aliases to str on Python 2.6. For that reason, it would seem like the code to work around this problem is simple: `if not isinstance(bytes, request.body): request.body.encode('utf-8')`

Indeed, I'd like to point out that this has worked around a bug in requests-wsgi-adapter: specifically, if provided a unicode string containing code points outside U+0000 to U+007F then the content-length would have been incorrect. Because we're now providing bytes to you, this error cannot occur. This change was introduced for exactly this reason.

**Comment by alexntt** [comment]
I've patched the library I depend on and our project so this is no longer an issue, thank you
