### ISSUE TITLE
2.11.0 causing issues with missing attribute 'reason' in raise_for_status()

### ISSUE THREAD

**Issue by robcresswell** [kennethreitz/requests#3494]
Apologies for the vague header, I'm still narrowing this down. It appears that this commit (https://github.com/kennethreitz/requests/commit/7700ecae14930fd078e28e35425661d46778bfa9) is using self.reason, and in our implementation, its throwing errors for a missing attribute 'reason'.

The lib in question is django_openstack_auth; all our tests began failing when 2.11.0 released. 2.10.0 still works fine. I'm unsure whether this is an issue with a clumsy test implementation on our side or a false assumption on the requests side. Will keep digging.

**Comment by Lukasa** [comment]
I suspect the issue is a bit of both. The higher level requests code expects a reason phrase, but they're not always common, especially in test implementations. That said, I recommend all test implementations _set_ a reason: the code here always expected one, it's just that now it's always checked for, rather than being checked for only in error cases.

If you have no reason phrase to set, just set `''`: that'll work fine.

**Comment by robcresswell** [comment]
Makes sense. This can be closed then, thanks for the quick response!

**Comment by Lukasa** [comment]
My pleasure!
