### ISSUE TITLE
requote_uri modifies URI

### ISSUE THREAD

**Issue by mocsar** [kennethreitz/requests#3546]
I would like to fetch
http://git.mycompany.com/api/v3/projects/my%2Ename%2Fmyproject/repository/commits?ref_name=master
but requote_uri transforms this URI to
http://git.mycompany.com/api/v3/projects/my.name%2Fmyproject/repository/commits?ref_name=master
what is an invalid URI for gitlab rest api.

**Comment by Lukasa** [comment]
Well, in the first instance you should consider contacting GitLab, because they clearly have a problem with their infrastructure. The period is a safe character in the path component of a URL, and as a result a URI that contains an unescaped period in the path must be treated exactly the same as one that contains an escaped period.

As to your issue, you can address this by using the [PreparedRequest flow](http://docs.python-requests.org/en/master/user/advanced/#prepared-requests), which will allow you to force the URL to any form you like without requote_uri getting in your way.

**Comment by mocsar** [comment]
Thank you!
