### ISSUE TITLE
test_lowlevel.py is failing in a Python 2 environment

### ISSUE THREAD

**Issue by Trodis** [kennethreitz/requests#3551]
If the Test test_lowlevel.py is being run by pytest in a Python 2 environment, the Testing fails at line 55 with an assertion error: assert len(fake_proxy.handler_results) == 1 is false because fake_proxy.handler_results is empty. The Problem could be as discussed on IRC, that a broken import is causing this failure, because pysocks for python 2 is not imported correct.

Running the same test file within the Python 3 environment, doesn't fail, the whole requests test suite is passed without an issue.

System: Arch Linux x64
Requests Version for Python 2 and 3: 2.11.1
PySocks Version for Python 2 and 3: 1.5.7  

![2016-09-05-181625_1245x1033_scrot](https://cloud.githubusercontent.com/assets/2480847/18253462/200a75b0-7395-11e6-9604-4ed3ebeb0ffb.png)

**Comment by Lukasa** [comment]
This error is a direct result of PySocks version 1.5.7, which when a SOCKS proxy is listening on only an IPv4 or IPv6 address but has routes available for both, connection setup can fail. This is fixed in the current master of PySocks, and can also be resolved by downgrading to PySocks 1.5.6 which does not support IPv6 addresses at all.

The best fix we can make here is the same as shazow/urllib3#964. Are you interested in contributing such a fix?

**Comment by nano3k0a** [comment]
Yes I would love to but, I need some direction what to do exactly

**Comment by Lukasa** [comment]
@Trodis Have you seen the fix in the linked PR?
