### ISSUE TITLE
"Requests is the only Non-GMO HTTP library for Python, safe for human consumption."

### ISSUE THREAD

**Issue by mouuff** [kennethreitz/requests#3556]
GMO are safe

**Comment by Lukasa** [comment]
This is _absolutely_ not the venue for this discussion.

**Comment by kennethreitz** [comment]
@Lukasa too serious

**Comment by kennethreitz** [comment]
@mouuff it's a joke :)

**Comment by mouuff** [comment]
https://github.com/drtshock/Potato

**Comment by kennethreitz** [comment]
@mouuff haha, behold—art!

**Comment by keikoro** [comment]
What _is_ GMO?

I'm wondering because it's in the first sentence of the repo's `README` and I've never heard of it and have no clue what it's supposed to mean in a programming context. I googled it and only came up with _genetically modified organism_. Is this some sort of in-joke I don't get?

**Comment by kennethreitz** [comment]
Yes :)

**Comment by Celthi** [comment]
I don't know the meaning either, and try to figure it out, but still puzzled.  I'm not a native English. @kerstin

**Comment by kennethreitz** [comment]
@Celthi it's a joke :)

**Comment by Celthi** [comment]
@kennethreitz  Oh, I see, :) :) :). Thank you.

**Comment by cornfeedhobo** [comment]
I think @kerstin's and @Celthi's reactions sums this up: this has no place in a README for such a widely depended on project.

Funny and confusing? Yes.
Professional? No.

@Lukasa If this is not the place for this discussion, then it probably shouldn't be in the README in the first place. Seems like complaining about an open invitation.

**Comment by kennethreitz** [comment]
Software is perfectly able to have a sense of humor.

**Comment by keikoro** [comment]
I hadn't thought about it in terms of professionalism – though maybe more because I feel like I can't prescribe what is and what isn't in contexts like these –, but yeah, the problem I see with it is more that inside jokes like this can be pretty confusing for people who are not native speakers of English and/or programming novices, and thus feel exclusionary. ("Is this something I should know about? If I don't, is it a problem?")

**Comment by richvdh** [comment]
I'm sorry to see that this issue has been closed out-of-hand. I absolutely agree that this is not the venue for a discussion of the merits of GMOs, but by including this sentence - whether it be a joke or not - you are implicitly aligning the requests project with one side of that debate.

If you still think this is just a joke rather than a political issue, consider how you would feel if it instead said "The only GMO-enhanced HTTP library for Python: nutritious and healthy". If your reaction to that sentence is also "haha, good joke" then well done: you really are impartial. But don't expect all your users to laugh it off in the same way.

Essentially, I consider your joke to be in poor taste. Perhaps we should also have a joke involving some racial stereotypes for completeness?

As others have already said: a software library should not be taking political sides. It's possible to have a sense of humour without doing so.

**Comment by keikoro** [comment]
I don't think I agree with the notion that software/libraries shouldn't take political sides ever. There's certainly code out there which is written specifically to help activists or spread awareness (about politicial issues, political figures and their actions etc.) or to make people stop and think (a good bunch of art-related code, I'd guess). In my opinion all of that is valid and even important as long as the motivations behind it aren't unsavory.

(Following that, I don't get why one would equate a critical stance on a controversial topic with dystopian qualities – which is how I read it – with racial jokes.)

It's fine if we disagree on this, I just don't want my previous comments to be misinterpreted. As stated above, I believe the issue is that the joke is inaccessible to a good portion of people wanting to use/using the library due to the potentially unfamiliar abbreviation and its general off-topic-ness, not because it's "taking a side".

**Comment by ghost** [comment]
Confused me as well. Maybe mentioning the fact it's a joke for non-native english?

**Comment by laneschmidt** [comment]
Life's too short to get caught up by stuff like this. Just ignore the joke if you cannot handle it.

**Comment by cornfeedhobo** [comment]
@laneschmidt your subtle pejorative is not missed. One could equally insult you with, "don't enter a conversation if you aren't mature enough to address people like adults" or even "life's too short to enter a conversation that you haven't meaningfully added to. Just delete your github account if you can't handle it".

**Comment by keikoro** [comment]
Echoing what @cornfeedhobo said, I was wondering why you, @laneschmidt, would trigger email notifications for everyone subscribed to this thread so far for what's basically a non-comment, thereby wasting all of our time, when you feel life's too short for stuff like this...

**Comment by geyang** [comment]
Whether GMO is safe is a serious scientific discussion because of all the miss-information out there. Implying that this statement is a joke and blame people for not getting it shows poor taste.

**Comment by GitHub-Mike** [comment]
To ensure that non native english speakers also understand this joke, no abbreviation should be used. A smiley at the end could also contribute to understanding. :-)

**Comment by ghost** [comment]
This joke is perfectly normal and should not be treated such seriously as "not professional" and confusing. This is just a tagline, *nothing else.*
@keikoro

**Comment by ryan-ccn** [comment]
This joke is perfectly normal and should not be treated such seriously as "not professional" and confusing. This is just a tagline, *nothing else.*
@keikoro

**Comment by LeHack** [comment]
@episodeyang is right. There is a lot of miss-information out there and joke-or-not it contributes to it.
It's ignoring such little stuff is what got us into this pseudoscientific mess of a world we have right now.
On the other hand I do appreciate a joke when I see one, especially in professional surroundings.
I'd just replace it with something like "Not tested on animals... they were too scared by the snake." or alike.

Update: I'd be equally concerned if it said "the only gluten free library", since that also while being a criminally overused marketing scheme (with no standing science proof, except for people with a very rare condition), would perpetuate pseudoscience myths (FUDs if you will) rather than be an innocent joke.

**Comment by silmeth** [comment]
Seems  to be finally resolved in the commit [7ca0e86a6752a5a763e5e82d94f34a522a976708](https://github.com/psf/requests/commit/7ca0e86a6752a5a763e5e82d94f34a522a976708#diff-04c6e90faac2675aa89e2176d2eec7d8).
