### ISSUE TITLE
convert all headers to bytes before invoking urllib3/httplib

### ISSUE THREAD

**Issue by stefanfoulis** [kennethreitz/requests#3573]
related to #3177 and shazow/urllib3#855

It's really easy to get this wrong. See sam-washington/requests-aws4auth#24 for an example.

**Comment by Lukasa** [comment]
There is no requirement for us to pass urllib3 bytes. urllib3's interface has always allowed native strings on the platform, which includes unicode on Python 3. The specific error you're looking at is one that we have already fixed in urllib3, so a fix will be coming down the pipe in the next few months. =)

**Comment by stefanfoulis** [comment]
@Lukasa what is the change in urllib3 that will solve this issue?

**Comment by Lukasa** [comment]
It's shazow/urllib3#719
