### ISSUE TITLE
Memory Bug in requests when being used with subprocess module.

### ISSUE THREAD

**Issue by KylePiira** [kennethreitz/requests#3612]
So I ran into this while working on a more complex project however here is a short demo to showcase the bug.
**NOTE:** I highly recommend you open some type of task viewer program to monitor RAM usage and know when to `Ctrl C` to prevent your OS from crashing.
# Steps to Reproduce:
a. Create Directory
b. Create two new files in the directory called script.py and queue.py
c. Put the following code into script.py:
```
import requests
```
d. Put the following code into queue.py:
```
from subprocess import call
call(['python','script.py'])
```
e. Now run the following command:
```
python script.py
```
Your computer should now begin rapidly using RAM and will eventually crash (took about 30 seconds for my Ubuntu install to crash on a rig with 8 GB of RAM.)

**Comment by drpoggi** [comment]
So this is happening because of how `six`, a package used by Requests, does its module discovery. You can confirm by changing `import requests` to `import six.moves.queue` (the line in `urllib3` causing this) and you'll get the same behavior. Your queue.py ends up getting imported and run, which obviously results in an infinite loop and your PC spawns Python processes until it crashes.

The solution is to name queue.py something else, preferably not a name shadowing a standard library module, because as you can see that can result in some very weird behavior and is generally considered a bad idea. If you want to file a bug with six their repo is [here](https://bitbucket.org/gutworth/six) but the simpler solution is probably you just change your filename.

**Comment by sigmavirus24** [comment]
@drpoggi is correct. There's not much to be done here within requests (or six for that matter). It's usually best to not to shadow the names of standard library modules.
