### ISSUE TITLE
Support 100-continue (expect100)

### ISSUE THREAD

**Issue by redixin** [kennethreitz/requests#3614]
This feature is used when client wants to check whether request body will be accepted by server before sending the body.

This is achieved by setting "Expect: 100-continue" request header. Server will respond with status line "100 Continue HTTP/1.1" if request headers are ok, or with actual full response if something goes wrong. Client should not send body if response was not "100 Continue HTTP/1.1"

Some useful links:

Related section in pep333:
 https://www.python.org/dev/peps/pep-0333/#http-1-1-expect-continue

How it looks like in aiohttp client (see expect100 parameter):
 http://aiohttp.readthedocs.io/en/stable/client_reference.html#basic-api

More detailed description:
 https://tools.ietf.org/html/rfc7231#section-5.1.1

**Comment by sigmavirus24** [comment]
Hi @redixin ,

After a quick search I found https://github.com/kennethreitz/requests/issues/713 which is an old issue that provides the reasoning for why Requests does not support this flow. In fact, this is because we are built on top of httplib. If you want to support 100-continue properly in Requests, you need to go convince the core python developers to support this first.

In the future, please search for similar issues.
