### ISSUE TITLE
form action without schema'ed ACTION fails with MissingSchema

### ISSUE THREAD

**Issue by chadmiller** [kennethreitz/requests#3618]
Used `requests` (and mechanicalsoup) to .get() a web page that has a form on it. The form tag looks like

`<form action="/submit_uri" method="post">`

I filled a part of the form, and then .submit()ed the form.

```
  File mechanicalsoup/browser.py", line 114, in submit
    request = self._prepare_request(form, url, **kwargs)
  File "mechanicalsoup/browser.py", line 109, in _prepare_request
    return self.session.prepare_request(request)
  File "requests/sessions.py", line 394, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "requests/models.py", line 294, in prepare
    self.prepare_url(url, params)
  File "requests/models.py", line 354, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '/submit_uri': No schema supplied. Perhaps you meant http:///submit_uri?
```

**Comment by StewPoll** [comment]
You're telling Requests to `get` at the URI of `/submit_uri` which isn't a valid URI.

You need to get the URI of the form, IE, `https://www.example.com` and add this to the URI before sending the `get` request.

**Comment by Lukasa** [comment]
Correct.

Resolving a URL you find in the HTML of a page into a gettable URL is an extremely complex operation, and Requests doesn't do it for you because it's fundamentally not a HTML library. The [WHATWG URL Specification](https://url.spec.whatwg.org) defines the logic for taking a base URL (the URL of the page you requested) and processing a URL on that page (in this case a path-absolute URL) into a new URL. Unfortunately, I am aware of no Python library that fully implements that logic at this time, but something like [rfc3986](http://pypi.python.org/pypi/rfc3986) is probably good enough.

**Comment by chadmiller** [comment]
Here's what I expect out of requests:

Methods that request pages newly take a context url, and interpret the passed in destination, pulling from the context url when necessary.

`get("foo", context="http://other/location/bar")`  gets `http://other/location/foo`

`get("/baz", context="http://other/location/bar")` gets `http://other/baz`

`get("://third/baz", context="https://other/location/bar")` gets `https://third/baz`

**Comment by Lukasa** [comment]
Why would you expect that out of Requests? Building URLs in this way is not a HTTP concern.

**Comment by sigmavirus24** [comment]
@chadmiller other libraries will do that for you (e.g., `rfc3986`) because they are not in the HTTP specification, they're in other (URI) specifications.
