### ISSUE TITLE
Use merge_environment_settings method in sessions.send method

### ISSUE THREAD

**Issue by yozel** [kennethreitz/requests#3626]
I work on a python project that uses requests. And as a developer, I have set that enviroment variables: HTTP_PROXY, HTTPS_PROXY and REQUESTS_CA_BUNDLE so I can see all of my requests with mitmproxy. Today, I have decided to use session.send() method with a prepared request instead of using .get(), .post() or .request(). But then, I realize that .send() doesn't respect my environment variables.

So, I think that merge_environment_settings method should be used in .send() method, instead of .request(). What do you think about that? Should I open a pull request for that?

**Comment by Lukasa** [comment]
@yozel Thanks for this issue!

Per #2807, this is intentional behaviour. `merge_environment_settings` is a public, documented method on the `Session`: if you're planning to move away from using `Session.request` to the prepared request flow, this is one of the things that needs to become part of your workflow if you want its behaviour.
