### ISSUE TITLE
If-Modified-Since is a "special" header?

### ISSUE THREAD

**Issue by miscellainiac** [kennethreitz/requests#3668]
I am using requests (2.10.0) in Python 2.7.11 and I just ran across some very strange behavior with respect to this header. I would like to send along different formats than 'Tue, 08 Nov 2016 05:00:00 GMT' which seems to be passed along just fine, but if I try a string like '2016-11-08T00:00:00-05:00' something is munging that value, fails to parse it (but does not raise an error) and my services on the other side get a completely different date (Thu, 31 Dec 2015 00:00:00 GMT).

So something is going on here, I'm just not sure where or even why. I am wondering if there is a way to simply pass along the string as-is...

**Comment by sigmavirus24** [comment]
@miscellainiac we do not (nor does anything between us and the socket) munge that header. My guess is that there's something infront of the server (e.g., a proxy or load balancer) that does this to your request header. Either way, the correct format is like your first example. See
- https://tools.ietf.org/html/rfc7231#section-5.2
- https://tools.ietf.org/html/rfc7232#section-3.3
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-Modified-Since

The first two are parts of the standard that define the behaviour and format of that header's value. The latter is a simplistic way of formatting it for ease.
