### ISSUE TITLE
Long timeout

### ISSUE THREAD

**Issue by looping84** [kennethreitz/requests#3692]
I need check my service is ok or not。 sometimes it will breakdown.

### how to reproduce the issue
```
 try:
    r = requests.get("http://xxx.com/",timeout=1)
    print(r.status_code)    
except requests.exceptions.Timeout:
	print 'timeout'
except requests.exceptions.RequestException as e:	
    print(e)
   
```
it always let me wait for 30 seconds

`I hope it only waits one second, if server doesn't response or the link is unreachable, throw exception`

below are exception message

> Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x3d344d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))

**Comment by Lukasa** [comment]
The requests timeout parameter is _per connection_, and Requests will make as many connection attempts as there are domain names. However, Requests cannot control the timeout of the DNS lookup, which is the problem here. Unfortunately, Python doesn't allow us any way around this problem: there is just no cross-platform way to do a DNS lookup with a timeout using the things installed by default.

Sorry!
