### ISSUE TITLE
Buggy servers with SNI give unrecognized_name

### ISSUE THREAD

**Issue by rudolphi** [kennethreitz/requests#3699]
When trying to open https://www.scbt.com with requests, an SSLError is raised, even though verify=False. Apache HttpClient has the same problem, but browsers open the page without any complaint. I was hoping requests would be more tolerant with such flawed servers, especially if the caller indicates that security is not of importance.
[stacktrace.txt](https://github.com/kennethreitz/requests/files/596393/stacktrace.txt)

Thanks!

Felix

**Comment by Lukasa** [comment]
Requests cannot be more tolerant of that server in the default configuration. The `unrecognized name` error you're seeing is an alert sent by the _remote server_: that is, our inability to set SNI means that the remote server is simply refusing to negotiate TLS with us. That means we cannot possibly be "tolerant" of that error: the remote server is being intolerant, not us.

I should note that the remote server's intolerance is _entirely_ reasonable. SNI is not an optional feature on the modern web, it's mandatory. For most other users I'd say that you should install the `requests[security]` extra, but right now that won't work because it relies on a CFFI extension and Jython has no support for CFFI at this time.

Unfortunately, that means that there's simply nothing we can do for you. Either Jython needs to add support for SNI, in which case Requests will automatically start using it, or Jython needs to add support for CFFI. Otherwise, however, we simply cannot help your use case.

**Comment by rudolphi** [comment]
Thanks very much for your quick reply! I was hoping to be able to imitate what the browser does, but it seems quite difficult indeed. Other servers using https work fine, but that particular one seems quite "tight". :-)

**Comment by Lukasa** [comment]
Sadly, the browser sends SNI, so it doesn't have this problem. 😞
