### ISSUE TITLE
Can't Get Version 2.2.1

### ISSUE THREAD

**Issue by PatriotRDX** [kennethreitz/requests#3716]
I have a program that won't run without version 2.2.0 or higher.

However, each time I try to install this with pip or easy_install, it only does 2.12.1 and even the --upgrade option says this is up to date.

I know this exists, since it's listed [here](https://pypi.python.org/pypi/requests/2.2.1), not to mention that this program requires it.

**Comment by nateprewitt** [comment]
@PatriotRDX have you tried using `pip install requests==2.2.1`?

Edit: Sorry, let me clarify for a moment. Are you looking for a version that is lower than 2.12 but higher than 2.2.0? The minor version number is linear, so 2.2.0 is an older version than 2.12.1.

**Comment by ghost** [comment]
@nateprewitt thanks this helped. However, it seems like [this documentation](https://pypi.python.org/pypi/requests/2.2.1) should be updated, since it's just flat out wrong.

**Comment by nateprewitt** [comment]
@PatriotRDX which part of the documentation do you feel is incorrect?

**Comment by ghost** [comment]
@nateprewitt the documentation here says to run `pip install requests` in Terminal. However, this only installs 2.12.1. Not to mention the documentation here is exactly the same as the documentation for 2.12.1.

**Comment by nateprewitt** [comment]
@PatriotRDX so this is a bit harder because this is a reflection of the README.rst at the time of release. `pip install requests` is the correct command for installing requests on your machine. If you require an older version, the standard usage of pip has you specify a specific version number (`requests==2.2.1`) or a range (`requests>=2.6.0`). You can find more documentation on pip [here](https://pip.pypa.io/en/stable/).

This should be specified by whichever package you're trying to use in either the requirements.txt file, or setup.py. If it isn't, that should probably be brought up with the package maintainer.

@Lukasa or Kenneth may have different opinions on retroactively updating older release docs, but I'm not sure it's likely.

**Comment by sigmavirus24** [comment]
@nateprewitt there is no way to update it. @PatriotRDX we expect users to have some understanding of how to specify requirements themselves and use pip.

**Comment by ghost** [comment]
> we expect users to have some understanding of how to specify requirements themselves and use pip.

@sigmavirus24 wow that's brutal, only time I've used Python has been today.

**Comment by nateprewitt** [comment]
@PatriotRDX, I think there's just been a bit of confusion with what you were asking. I took a peek at the repository you're using and the requirements.txt is configured correctly. 2.12.1 is the latest release of Requests which satisfies the requirements of `requests>=2.2.0`.

If you use the command `pip install -r requirements.txt` in the future, version handling should be taken care of for you. `pip` is the standard package manager for Python, so you typically won't have to worry about downloading anything via your browser.

Hopefully this helps.

**Comment by ghost** [comment]
@nateprewitt thank you for your help. I still get an error when running 2.12.1, so I'll just stick to 2.2.1 for now. Thank you again.

**Comment by ghost** [comment]
This sounds like a [XY problem](http://xyproblem.info/). If the error you get is caused by Requests, you could open an issue here that describes the problem.

**Comment by ghost** [comment]
@lutzhorn my issue was solved by @nateprewitt at the beginning of this thread. I don't have any other problems that need to be solved.

**Comment by ghost** [comment]
>  I still get an error when running 2.12.1, so I'll just stick to 2.2.1 for now.

That sounds like a problem to me.

**Comment by ghost** [comment]
@lutzhorn it doesn't matter, as long as it works, it works. I don't need 2.12.1, this is only one small program I'm testing out.

**Comment by ghost** [comment]
@nateprewitt, @lutzhorn, @sigmavirus24 thank you all for your help. Have a nice day.

**Comment by drpoggi** [comment]
For posterity, it's not a requests problem. It was due to some pretty poor version checking in the project he was using. @PatriotRDX the error you're getting was fixed [here](https://github.com/wummel/linkchecker/commit/c2ce810c3fb00b895a841a7be6b2e78c64e7b042) if you care to follow it, however that fix isn't on PyPi which is why you're still seeing the error.

**Comment by ghost** [comment]
@drpoggi thank you for the extra information on my other issue. I've got it working with 2.2.1 so it doesn't matter to me, however, someone else may find it useful.
