### ISSUE TITLE
Is there a specific reason why there is no CI (Travis/Appveyor)?

### ISSUE THREAD

**Issue by obestwalter** [kennethreitz/requests#3739]
I was surprised to see that requests is not making use of Travis/Appveyor CI. Is there a specific reason for that?

I would be willing to send a PR implementing it, if the only reason is that no one got around to it yet.

I also saw that `tox.ini` is in the .gitignore file - so is tox used locally by some devs but not part of the project? If so: what are the reasons for not having a `tox.ini` as part of the project? I would use tox.ini to integrate the project with the CI systems and also add a convenient way to run the tests on different interpreters.

**Comment by nateprewitt** [comment]
Hey @obestwalter, I talked to @Lukasa about this a few weeks ago. To quote a bit of his response:

>Requests moved away from Travis because it made a lot of live network requests in its test suite and Travis had frequent network outages that caused real problems with the test run. 

While a lot of these issues have been resolved, I think the general sentiment is Travis generates a fair amount of noise for the repo owner and has historically had quirks. Until recently, Requests ran CI on a Jenkins server, but that's since been removed.

As for tox, I think most of Requests' contributors are running a local tox.ini file for testing changes. If you run that in conjunction with something like [pyenv](https://github.com/yyuu/pyenv), you have an easy local equivalent of a Travis environment which has worked for the most part the last several months.

Note this may no longer be the state of things, I just wanted save Lukasa from having to reiterate what he's conveyed recently via other channels.

Here's the last couple of Kenneth's comments on the state of Requests' CI/Travis in 2016 too. [[Feb](https://github.com/kennethreitz/requests/pull/2991#issuecomment-178813436)] [[Apr](https://github.com/kennethreitz/requests/pull/3096#issuecomment-211701179)]

**Comment by Lukasa** [comment]
@obestwalter All of these decisions are fundamentally @kennethreitz's: the other maintainers have no objection to re-adding Travis support and a toxfile.

**Comment by obestwalter** [comment]
Hello @Lukasa and @nateprewitt,

thanks for the explanation. Why is the tox.ini then not part of the project? Is there a problem to get it working for everyone involved? My naive thinking would be that once you have tox properly configured for the project it works for everyone involved. 

So, if there are any concrete problems/bugs that prevent your project from adopting tox properly, just let us know here: https://github.com/tox-dev/tox (yes, we finally moved to Github :)).

**Comment by Lukasa** [comment]
We have adopted tox heavily, but Kenneth didn't want a toxfile checked into the repository: that's why it's not part of the project. =) Once again, these particular decisions are made by Kenneth.

**Comment by obestwalter** [comment]
Thank you - I was pointed to the relevant discussions. I should have looked a bit more closely before asking stupid questions. Sorry for the noise.
