### ISSUE TITLE
Max_redirect = 0; Location header missing

### ISSUE THREAD

**Issue by arao-nnl** [kennethreitz/requests#3747]
Hi,
Requests ver: 2.11.1

I'm using a session object (s) to make a POST to a specific URL:
r=s.send(prepared)

I expect this to return 302, which is happening.
I set s.max_redirects=0 because I don't want Requests to automatically visit the new URL.
So, I promptly receive a TooManyRedirects exception, which is good.
However, in the exception handler, I'm unable to get hold of the header 'Location'.
The response object itself is empty.

I debugged it and saw that the Location header was captured correctly. But, when the exception is thrown, it's all gone.

(Pdb) n
> /Library/Python/2.7/site-packages/requests/adapters.py(275)build_response()
-> return response
(Pdb) response
<Response [302]>
(Pdb) response.__dict__
{'cookies': <RequestsCookieJar[]>, '_content': False, 'headers': {'Date': 'Fri, 02 Dec 2016 22:27:44 GMT', 'Content-Length': '0', 'Location': 'http://XXX:8080/openam?goto=https:YYY', 'Server': 'Apache-Coyote/1.1'}, 'url': u'https://XXX:8443/proxyplus/nnl/reg', 'status_code': 302, '_content_consumed': False, 'encoding': None, 'request': <PreparedRequest [POST]>, 'connection': <requests.adapters.HTTPAdapter object at 0x1053ae1d0>, 'elapsed': datetime.timedelta(0), 'raw': <requests.packages.urllib3.response.HTTPResponse object at 0x1055e3550>, 'reason': 'Found', 'history': []}

As you can see, 'Location' is found at this stage in 'response', but when the exception is thrown, response becomes empty.

Thanks!

**Comment by nateprewitt** [comment]
Hey @arao-nnl, in order to get the behaviour you're looking for, you'll need to use a slightly different mechanism. `max_redirects` is intended to raise an exception halting the request in the event of a redirection loop, or excessive redirects.

For your issue of trying to simply halt before a redirect is performed, I suggest using the `allow_redirects` parameter. This will retrieve the 302 and then leave the object untouched until you decide how to proceed (such as only reading the Location header).

```python
s = requests.Session()
r = requests.Request('GET', 'http://httpbin.org/redirect-to?url=get')
resp = s.send(r.prepare(), allow_redirects=False)
loc = resp.headers['Location']
```
