### ISSUE TITLE
Customized proxies seems not work, how can we know the proxies's IP address send to server?

### ISSUE THREAD

**Issue by withr** [kennethreitz/requests#3798]
Take this as an example: 

```
#!/usr/bin/env python
# -*- coding: utf-8 -*-

import requests 

proxies = {"http":"http://111.222.333.444:80"}
r = requests.get("https://www.google.com", proxies=proxies, timeout=5)
r.status_code
r.content 
```

Obviously, the proxies "111.222.333.444" is not correct, but why I still got status_code 200??

How can we check the proxies we used to send to server?

**Comment by Lukasa** [comment]
The `proxies` dictionary is defined as having the following form: the keys are the URL schemes for the URLs you are requesting, and the values are the URLs for reaching the proxy.

That means when we make a web request, we take the scheme of the URL you're requesting and look for a proxy for it. In your case, the scheme is `https` (because you're looking for `https://www.google.com`). Your proxy dictionary has no `https` key, so that means "no proxy", so we just go directly to Google.

If you change your `requests.get` to be `http://www.google.com`, then you'll find that we attempt to reach the proxy and error out.

**Comment by withr** [comment]
Thanks, so rapid reply!!
Can you also reply the second question: can we retrieve the proxies send to server? some time, I got error, and I am pretty sure the schemes are same but still got an error, like use free proxies, some of them may out of date.

**Comment by Lukasa** [comment]
@withr Unfortunately, not easily. Generally speaking you should look at the proxies dictionary you provided. Alternatively, you can write a custom Transport Adapter that will provide the information you need, though that's quite a lot of work.
