### ISSUE TITLE
Why LifoQueue and not simply Queue (or custom LifoQueue)?

### ISSUE THREAD

**Issue by Kronuz** [kennethreitz/requests#3799]
During some profiling, I found out one slow operation is `self.pool.get()` in `_get_conn()`.

In urllib3, in `connectionpool.ConnectionPool`, requests uses `LifoQueue` (which uses a list instead of a much faster deque):
https://github.com/kennethreitz/requests/blob/master/requests/packages/urllib3/connectionpool.py#L64

My suggestion is one could use a custom LifoQueue as:
```python
class LifoQueue(Queue):
    def _get(self):
        return self.queue.pop()
```
or simply use a Queue, if Lifo is not really needed.

**Comment by Lukasa** [comment]
The LIFO property of the LifoQueue is very much needed: this is to ensure the increased likelihood of using a warm TCP connection, which provides substantial efficiency bonuses. The reason it's a queue, instead of just a deque, is to get the thread-safety guarantees that the queue module provides.

You are welcome to attempt to optimise this, but those two semantics need to be preserved. I suspect you'll find that the major performance cost is actually the locking, and by the time you reintroduce that the perf gains are minimal.

**Comment by sigmavirus24** [comment]
Further the code you're linking to is actually in urllib3, thus making this not only an invalid defect report but also one on the wrong project.
