### ISSUE TITLE
Proxy and SSL : the CONNECT request fails on some proxy (cntlm) as the request is HTTP 1.0 instead of 1.1

### ISSUE THREAD

**Issue by LaurentChardin** [kennethreitz/requests#3816]
It looks like requests (or urllib3 ?) is creating a CONNECT request that fails with some proxies when trying to initiate the SSL tunnel:

INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): api.hipchat.com
send: 'CONNECT api.hipchat.com:443 HTTP/1.0\r\n'
send: '\r\n'

as we can, it generates an HTTP/1.0 header which seems to be inaccurate. I could not find any definition of the CONNECT command in the HTTP/1.0 RFC, and seems to have been really defined in HTTP 1.1 RFC.

By manually telneting to my cntlm, i could make the CONNECT work by replacing 1.0 by 1.1.

This makes the requests library fail to work on my side where i have to use CNTLM because our usual proxy is using Kerberos/CNTLM for authentication. 

Is there any way to have this reviewed ?

best,

**Comment by Lukasa** [comment]
Unfortunately, this is not something we can easily change in urllib3 at the moment, because this CONNECT is actually created by httplib. Simply changing to HTTP/1.1 is not sufficient because that CONNECT request is then not HTTP/1.1 compliant (it has no `Host` header field). We'd need to change both.

Ultimately, the upcoming urllib3 v2 release will resolve this issue by removing our dependence on httplib. Until then, the only way to fix this is to monkeypatch or override httplib's `tunnel()` logic.

**Comment by LaurentChardin** [comment]
Found some additional information here : http://stackoverflow.com/questions/1841730/how-can-urllib2-httplib-talk-http-1-1-for-https-connections-via-a-squid-proxy/1841740#1841740
