### ISSUE TITLE
Unsupported authorization method

### ISSUE THREAD

**Issue by thewebsitedev** [kennethreitz/requests#3850]
Hello,

My code:
```
headers = {'Authorization': 'Bearer '+access_token}
payload = {'grant_type':'refresh_token','refresh_token':refresh_token,'client_id': client_id, 'client_secret': client_secret}
resp = requests.post(url,headers=headers,data=payload).json()
```

I am trying to get refresh token as mentioned in the [docs](https://build.envato.com/api/#oauth) for Envato API.

When I run this code I get the following response:
**{'error': 'invalid_request', 'error_description': 'Unsupported authorization method: '}**

Can anyone point out as to what I am missing here?

As per the docs I need to make a POST request to get the refresh token.
```
POST https://api.envato.com/token
     grant_type=refresh_token&
     refresh_token=[REFRESH_TOKEN]&
     client_id=[CLIENT_ID]&
     client_secret=[CLIENT_SECRET]
```

**Comment by Lukasa** [comment]
So, this is not really a Requests problem: the problem is with the specific data you need to send in the OAuth flow.

However, can I suggest you try removing the `Authorization` header? This uses the `token` endpoint, which some of the other requests do, and none of the others provide an `Authorization` header. I suggest trying that.

**Comment by thewebsitedev** [comment]
I totally agree. Thank you so much!
