### ISSUE TITLE
idea - `Response.response_flow` or `Response.response_chain` convenience method

### ISSUE THREAD

**Issue by jvanasco** [kennethreitz/requests#3931]
We consume a lot of URL shorteners and redirects. Unlike many requests users, we care about the entire journey -- not just the destination.  The current API makes it slightly inconvenient to iterate over the responses in order when needed. 

I often end up using a function that does the following, and wanted to suggest handling this upstream with something like...

    @property
    def response_chain(self):
        '''iterate over the responses in order, from the original request to ultimate response'''
        if self.history:
            for response in self.history:
                yield response
        if self.response:
            yield self.response

**Comment by Lukasa** [comment]
So, my initial inclination is to say that this isn't likely to get in. Our general rule is that a feature request must meet at least two of the following criteria:

1. Be generally useful: that is, be valuable for a large number of our users. 
2. Be complex or subtle to implement, in such a way that will make it difficult for other users. 
3. Rely on private parts of the codebase that we may change or break otherwise. 

This is none of those things as far as I can see: it's simple to implement, moderately widely useful but not anything like 50% of users, and relies entirely on published parts of the API. So I'm inclined to say there isn't much value add in bringing that code in. Does that make sense?

**Comment by jvanasco** [comment]
I'm 100% fine with it not being implemented upstream.  I think maybe 10% of users would find this useful.  I've just done this enough times to think it was worth discussing.

**Comment by Lukasa** [comment]
Agreed, you should always feel tee to propose new feature ideas. It's just worth knowing what our policy is on them. 😁

Thanks for the suggestion!
