### ISSUE TITLE
Disabling SSL verification at application level 

### ISSUE THREAD

**Issue by rnagpal** [kennethreitz/requests#3940]
Is there a way to disable SSL verification at my application level? 

I'm using the requests module which allows be to disable it per request level(by setting verify to false) but I wanted to way to disable for all requests. I'm running my tests against my local emulator, so I don't need that check and hence want to disable it at my application(test) level.

I'm looking for something like process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0" as used in Node.js

I'm on Python 2.7

**Comment by Lukasa** [comment]
Thanks for reaching out!

There is no way to do this, no. This is quite deliberate: such a setting is what I'd call an "attractive nuisance". Put another way, it's a setting that users are likely to attempt to use rather than solving the problem they have. Worse, it's a setting that is easily enabled and then forgotten, causing users to put themselves at enormous risk unexpectedly and silently.

Generally I'd recommend resolving the actual problem by locating all the relevant root certificates you need and bundling them. That way you get the security benefits of HTTPS *and* a functioning application, rather than sacrificing the former for the latter.

Hope that helps!

**Comment by rnagpal** [comment]
@Lukasa Thanks for your comments!

I was able to resolve this by explicitly specifying the certificate like below:
os.environ["REQUESTS_CA_BUNDLE"] = "F:/emulator_certificate.cer"

I wanted to avoid checking-in this certificate in my file system for running my automated tests. Is there a way in which Python can look into my Windows Certification Manager store to see if this certificate is installed and use it rather than me having to explicitly export it and provide it as above?

**Comment by Lukasa** [comment]
So you can use [wincertstore](https://pypi.python.org/pypi/wincertstore). Otherwise, we need to wait for [PEP 543](https://www.python.org/dev/peps/pep-0543/).

**Comment by rnagpal** [comment]
@Lukasa Thanks for the suggestion!
I went ahead and used wincertstore and it works without me having to extract and specify the certificate.
