### ISSUE TITLE
requests.put redirect from http to https doesn't forward JSON payload

### ISSUE THREAD

**Issue by colekas-csc** [kennethreitz/requests#3942]
Python version - 2.7.12
Requests version - 2.13.0

I was incorrectly hitting an internal server with an put http request versus an https and the json=<blah> blob doesn't appear to be passed through. The headers and params keys do appear to be passed through.

**Comment by nateprewitt** [comment]
Hey @colekas-csc, this is intended functionality in Requests 2.13.0. When Requests receives a redirect, it strips the payload to prevent unintentional transfer of information to the wrong server. We're a tad overzealous with this right now which is why this behavior will be modified in 3.0.0, but for now we must maintain this for backwards compatibility.

Thanks for taking the time to check in on this though!
