### ISSUE TITLE
Use libproxy gain WPAD/PAC support for free

### ISSUE THREAD

**Issue by marceloslacerda** [kennethreitz/requests#3961]
Currently requests does figuring out of whether a proxy should be used for a given URL. [WPAD/PAC](https://en.wikipedia.org/wiki/Web_Proxy_Auto-Discovery_Protocol) files describe those requirements, so if requests were to support WPAD proxy descriptions it would need to also parse it and figure what proxy to use for what URL.

On the other hand requests could delegate that task to libproxy and clean up a bunch of code (and issues) from the project.

**Comment by marceloslacerda** [comment]
By the way since I'm interested I could help implementing it.

**Comment by Lukasa** [comment]
So Requests cannot easily use libproxy because it is a binary dependency. We therefore cannot vendor it, and so cannot unconditionally rely on it being present. I would be open to a series of patches that add support, but libproxy is also not (as far as I can see) downloadable from PyPI either.

All of this together suggests that adding optional libproxy support would provide minimal benefit: an overwhelming majority of users do not have access to libproxy, and we have no way to distribute it to them.

My suggestion, then, is that someone (anyone who wants to be helpful) starts distributing binary wheels of libproxy on PyPI. At that point, once there is a reliable distribution method, we can discuss how reasonable it is to have Requests migrate to use it. However, until that time it's just not practical for Requests to add that dependency.

Sorry!

**Comment by sdementen** [comment]
I think pypac (https://pypac.readthedocs.io/en/latest/) is offering this functionality, correct ?
Should it be integrated / merged in some way to requests ?
The could allow a proxies="pac" kind of functionality out of the box.

**Comment by marceloslacerda** [comment]
Yeah seems like it should work. I'll see if I can get it to function at work.
