### ISSUE TITLE
Install in Docker does not work as expected

### ISSUE THREAD

**Issue by PetaPetaPeta** [kennethreitz/requests#3999]
I am attempting to build a Docker image (base image ubuntu:14.04) on a Windows machine where one of the commands are:
```
RUN pip install git+https://github.com/kennethreitz/requests
```
The functionality of this is to use pip inside the container to install the latest version of requests. It has functioned correctly in the past, but it currently throws an error. 
```
Step X/Y : RUN pip install git+https://github.com/kennethreitz/requests
 ---> Running in 33fa1f8103a0
Downloading/unpacking git+https://github.com/kennethreitz/requests
  Cloning https://github.com/kennethreitz/requests to /tmp/pip-ZPkqbQ-build
  Running setup.py (path:/tmp/pip-ZPkqbQ-build/setup.py) egg_info for package from git+https://github.com/kennethreitz/requests
    error in requests setup command: Invalid environment marker: platform_system == "Windows" and python_version<"3.3"
    Complete output from command python setup.py egg_info:
    error in requests setup command: Invalid environment marker: platform_system == "Windows" and python_version<"3.3"
```
The error is being triggered by the following extra requirement introduced [here](
https://github.com/kennethreitz/requests/commit/d89f8c0d70195d1ee707426ac7f3bdab870e0a18#diff-2eeaed663bd0d25b7e608891384b7298R100). 

The correct thing to do in this case is of course to lock the version of requests in the `pip install`-command and I have done this. I do however suspect that this could be an issue in the future if this commit is released.

**Comment by Lukasa** [comment]
This error is caused because the version of `pip` and `setuptools` being used in Ubuntu 14.04 is extremely old (necessarily it's from before 2014), and so doesn't understand markers. Frankly, that doesn't bother me very much. Assuming you're using a virtualenv inside your Docker image, you can resolve this by running `pip install -U setuptools` and `pip install -U pip` and that will fix your problems. If you aren't, you shouldn't be installing from `pip` as you'll totally bust your OS.

**Comment by sigmavirus24** [comment]
Hi @PetaPetaPeta thanks for opening this, but as @Lukasa explained there is nothing we can do to fix this for ancient versions of pip and setuptools. As such, I'm closing this issue.
