### ISSUE TITLE
The case of the haunted stream request

### ISSUE THREAD

**Issue by jacquerie** [kennethreitz/requests#4035]
Hi,

I'm not sure if this is a bug in `requests` or a misconfiguration in the server I'm interacting with, but I have the following very puzzling result:
```python
>>> from requests import get
>>> response = get('http://edok01.tib.uni-hannover.de/edoks/e01dh15/815761511.pdf', stream=True)
>>> next(response.iter_content(4))
'%PD'
```
which returns 3 characters instead of the 4 that I requested, but also:
```python
>>> from requests import get
>>> response = get('http://edok01.tib.uni-hannover.de/edoks/e01dh15/815761511.pdf', stream=True)
>>> iter = response.iter_content(1)
>>> next(iter)
'%'
>>> next(iter)
'P'
>>> next(iter)
'D'
>>> next(iter)
'F'
```
which instead returns all the 4 characters. Note also that this happens with both `unicode_decode=True` or `unicode_decode=False`.

How is this possible? This is happening with `requests==2.14.2`. The description of the problem in https://github.com/kennethreitz/requests/issues/3980#issue-223287665 looks relevant, but its fix in #3984 looks less relevant. In fact, I still see the problem on a local checkout of `master`.

**Comment by Lukasa** [comment]
`iter_content` transparently decompresses gzipped data received from the server. This means that when we receive bytes from the network we don't know how many bytes that will actually resolve into. For that reason, we don't guarantee that you'll get literally that number of bytes: we just promise that you won't get the empty string. That's why `iter_content(1)` appears to "work".

This is the expected behaviour, I'm afraid.

**Comment by jacquerie** [comment]
Ah, thanks a lot. At one point I had the feeling it had something to do with compression, but I didn't investigate in that direction.
