### ISSUE TITLE
Failed to establish a new connection: [Errno 11003] getaddrinfo failed

### ISSUE THREAD

**Issue by Abysssssss** [kennethreitz/requests#5073]
If you try to install a module through pip, it generates this error. What just did not try. I could install packages by downloading from official sites, but I can’t do it, so this method is needed, and it’s also much more convenient. There was an option to use --proxy=user:pass@host:port, but I do not know what to enter in user, pass, host and port. I use the development environment Sublime Text, version of python 3.7.3. Very urgently, I rummaged through a bunch of sites - I did not find anything. I would be extremely grateful to the decision.
![1](https://user-images.githubusercontent.com/50078144/56865779-79dfae00-69da-11e9-8bd3-ebb14c4480d8.jpg)
When using easy_install:
![1 1](https://user-images.githubusercontent.com/50078144/56866013-5e29d700-69dd-11e9-86e0-aa93501c805a.jpg)

**Comment by Dahlin** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    I can install the numpy module through pip successful ,it not generate error. My environment:Python3.7.2;pip19.0.3;win10 professional Edition I don't have python2 in my operating system.
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                dahlinsky
                            
                    
                        
                            
                                    dahlinsky@qq.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    On 4/28/2019 22:25，Abysssssss<notifications@github.com> wrote： 


If you try to install a module through pip, it generates this error. That just did not try. I could install packages by downloading from official sites, but I can’t do it, so this method is needed, and it’s also much more convenient. There was an option to use --proxy=user:pass@host:port, but I do not know what to enter in user, pass, host and port. I use the development environment Sublime Text. Very urgently, I rummaged through a bunch of sites - I did not find anything. I would be extremely grateful to the decision.





—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
