### ISSUE TITLE
Why stopped Python 3.4 support?

### ISSUE THREAD

**Issue by jerrymakesjelly** [kennethreitz/requests#5098]
I found that PR #5092 has stopped support for Python 3.4, but I couldn't find the reasons

Can someone tell me why?

**Comment by nateprewitt** [comment]
Hi @jerrymakesjelly, we discontinued support for 3.4 due to it [reaching end of life](https://www.python.org/dev/peps/pep-0429/#release-schedule) and no longer receiving updates. Many of our upstream dependencies have dropped support including some of our testing infrastructure.

Thanks for checking in on this!

**Comment by jerrymakesjelly** [comment]
@nateprewitt Thank you!
